module Docker
  module Models
    type auth_response = { status: String, identity_token: String }

    class AuthResponse < Docker::Internal::Type::BaseModel
      attr_accessor status: String

      attr_reader identity_token: String?

      def identity_token=: (String) -> String

      def initialize: (status: String, ?identity_token: String) -> void

      def to_hash: -> { status: String, identity_token: String }
    end
  end
end
