module Docker
  module Models
    type container_stop_params =
      { signal: String, t: Integer }
      & Docker::Internal::Type::request_parameters

    class ContainerStopParams < Docker::Internal::Type::BaseModel
      extend Docker::Internal::Type::RequestParameters::Converter
      include Docker::Internal::Type::RequestParameters

      attr_reader signal: String?

      def signal=: (String) -> String

      attr_reader t: Integer?

      def t=: (Integer) -> Integer

      def initialize: (
        ?signal: String,
        ?t: Integer,
        ?request_options: Docker::request_opts
      ) -> void

      def to_hash: -> {
        signal: String,
        t: Integer,
        request_options: Docker::RequestOptions
      }
    end
  end
end
