module Docker
  module Models
    type container_start_params =
      { detach_keys: String } & Docker::Internal::Type::request_parameters

    class ContainerStartParams < Docker::Internal::Type::BaseModel
      extend Docker::Internal::Type::RequestParameters::Converter
      include Docker::Internal::Type::RequestParameters

      attr_reader detach_keys: String?

      def detach_keys=: (String) -> String

      def initialize: (
        ?detach_keys: String,
        ?request_options: Docker::request_opts
      ) -> void

      def to_hash: -> {
        detach_keys: String,
        request_options: Docker::RequestOptions
      }
    end
  end
end
