module Docker
  module Models
    type error = { message: String }

    class Error < Docker::Internal::Type::BaseModel
      attr_accessor message: String

      def initialize: (message: String) -> void

      def to_hash: -> { message: String }
    end
  end
end
