module Docker
  module Models
    type image_delete_params =
      { force: bool, noprune: bool, platforms: ::Array[String] }
      & Docker::Internal::Type::request_parameters

    class ImageDeleteParams < Docker::Internal::Type::BaseModel
      extend Docker::Internal::Type::RequestParameters::Converter
      include Docker::Internal::Type::RequestParameters

      attr_reader force: bool?

      def force=: (bool) -> bool

      attr_reader noprune: bool?

      def noprune=: (bool) -> bool

      attr_reader platforms: ::Array[String]?

      def platforms=: (::Array[String]) -> ::Array[String]

      def initialize: (
        ?force: bool,
        ?noprune: bool,
        ?platforms: ::Array[String],
        ?request_options: Docker::request_opts
      ) -> void

      def to_hash: -> {
        force: bool,
        noprune: bool,
        platforms: ::Array[String],
        request_options: Docker::RequestOptions
      }
    end
  end
end
