module Docker
  module Models
    type network_delete_params =
      {  } & Docker::Internal::Type::request_parameters

    class NetworkDeleteParams < Docker::Internal::Type::BaseModel
      extend Docker::Internal::Type::RequestParameters::Converter
      include Docker::Internal::Type::RequestParameters

      def initialize: (?request_options: Docker::request_opts) -> void

      def to_hash: -> { request_options: Docker::RequestOptions }
    end
  end
end
