module Docker
  module Models
    type network_list_params =
      { filters: String } & Docker::Internal::Type::request_parameters

    class NetworkListParams < Docker::Internal::Type::BaseModel
      extend Docker::Internal::Type::RequestParameters::Converter
      include Docker::Internal::Type::RequestParameters

      attr_reader filters: String?

      def filters=: (String) -> String

      def initialize: (
        ?filters: String,
        ?request_options: Docker::request_opts
      ) -> void

      def to_hash: -> {
        filters: String,
        request_options: Docker::RequestOptions
      }
    end
  end
end
