module Docker
  module Models
    type service_create_params =
      { spec: Docker::ServiceCreateParams::Spec, x_registry_auth: String }
      & Docker::Internal::Type::request_parameters

    class ServiceCreateParams < Docker::Internal::Type::BaseModel
      extend Docker::Internal::Type::RequestParameters::Converter
      include Docker::Internal::Type::RequestParameters

      attr_accessor spec: Docker::ServiceCreateParams::Spec

      attr_reader x_registry_auth: String?

      def x_registry_auth=: (String) -> String

      def initialize: (
        spec: Docker::ServiceCreateParams::Spec,
        ?x_registry_auth: String,
        ?request_options: Docker::request_opts
      ) -> void

      def to_hash: -> {
        spec: Docker::ServiceCreateParams::Spec,
        x_registry_auth: String,
        request_options: Docker::RequestOptions
      }

      type spec = {  }

      class Spec < Docker::Models::Spec
        def initialize: -> void

        def to_hash: -> {  }
      end
    end
  end
end
