module Docker
  module Models
    type service_list_params =
      { filters: String, status: bool }
      & Docker::Internal::Type::request_parameters

    class ServiceListParams < Docker::Internal::Type::BaseModel
      extend Docker::Internal::Type::RequestParameters::Converter
      include Docker::Internal::Type::RequestParameters

      attr_reader filters: String?

      def filters=: (String) -> String

      attr_reader status: bool?

      def status=: (bool) -> bool

      def initialize: (
        ?filters: String,
        ?status: bool,
        ?request_options: Docker::request_opts
      ) -> void

      def to_hash: -> {
        filters: String,
        status: bool,
        request_options: Docker::RequestOptions
      }
    end
  end
end
