module Docker
  module Models
    type system_version_response =
      {
        api_version: String,
        arch: String,
        build_time: String,
        components: ::Array[Docker::Models::SystemVersionResponse::Component],
        experimental: bool,
        git_commit: String,
        go_version: String,
        kernel_version: String,
        min_api_version: String,
        os: String,
        platform: Docker::Models::SystemVersionResponse::Platform,
        version: String
      }

    class SystemVersionResponse < Docker::Internal::Type::BaseModel
      attr_reader api_version: String?

      def api_version=: (String) -> String

      attr_reader arch: String?

      def arch=: (String) -> String

      attr_reader build_time: String?

      def build_time=: (String) -> String

      attr_reader components: ::Array[Docker::Models::SystemVersionResponse::Component]?

      def components=: (
        ::Array[Docker::Models::SystemVersionResponse::Component]
      ) -> ::Array[Docker::Models::SystemVersionResponse::Component]

      attr_reader experimental: bool?

      def experimental=: (bool) -> bool

      attr_reader git_commit: String?

      def git_commit=: (String) -> String

      attr_reader go_version: String?

      def go_version=: (String) -> String

      attr_reader kernel_version: String?

      def kernel_version=: (String) -> String

      attr_reader min_api_version: String?

      def min_api_version=: (String) -> String

      attr_reader os: String?

      def os=: (String) -> String

      attr_reader platform: Docker::Models::SystemVersionResponse::Platform?

      def platform=: (
        Docker::Models::SystemVersionResponse::Platform
      ) -> Docker::Models::SystemVersionResponse::Platform

      attr_reader version: String?

      def version=: (String) -> String

      def initialize: (
        ?api_version: String,
        ?arch: String,
        ?build_time: String,
        ?components: ::Array[Docker::Models::SystemVersionResponse::Component],
        ?experimental: bool,
        ?git_commit: String,
        ?go_version: String,
        ?kernel_version: String,
        ?min_api_version: String,
        ?os: String,
        ?platform: Docker::Models::SystemVersionResponse::Platform,
        ?version: String
      ) -> void

      def to_hash: -> {
        api_version: String,
        arch: String,
        build_time: String,
        components: ::Array[Docker::Models::SystemVersionResponse::Component],
        experimental: bool,
        git_commit: String,
        go_version: String,
        kernel_version: String,
        min_api_version: String,
        os: String,
        platform: Docker::Models::SystemVersionResponse::Platform,
        version: String
      }

      type component = { name: String, version: String, details: top? }

      class Component < Docker::Internal::Type::BaseModel
        attr_accessor name: String

        attr_accessor version: String

        attr_accessor details: top?

        def initialize: (name: String, version: String, ?details: top?) -> void

        def to_hash: -> { name: String, version: String, details: top? }
      end

      type platform = { name: String }

      class Platform < Docker::Internal::Type::BaseModel
        attr_accessor name: String

        def initialize: (name: String) -> void

        def to_hash: -> { name: String }
      end
    end
  end
end
