module Docker
  module Models
    type volume_delete_params =
      { force: bool } & Docker::Internal::Type::request_parameters

    class VolumeDeleteParams < Docker::Internal::Type::BaseModel
      extend Docker::Internal::Type::RequestParameters::Converter
      include Docker::Internal::Type::RequestParameters

      attr_reader force: bool?

      def force=: (bool) -> bool

      def initialize: (
        ?force: bool,
        ?request_options: Docker::request_opts
      ) -> void

      def to_hash: -> { force: bool, request_options: Docker::RequestOptions }
    end
  end
end
