module DockerEngine
  module Models
    type config_update_params =
      { version: Integer } & DockerEngine::Internal::Type::request_parameters

    class ConfigUpdateParams < DockerEngine::Internal::Type::BaseModel
      extend DockerEngine::Internal::Type::RequestParameters::Converter
      include DockerEngine::Internal::Type::RequestParameters

      attr_accessor version: Integer

      def initialize: (
        version: Integer,
        ?request_options: DockerEngine::request_opts
      ) -> void

      def to_hash: -> {
        version: Integer,
        request_options: DockerEngine::RequestOptions
      }
    end
  end
end
