module DockerEngine
  module Models
    type container_delete_params =
      { force: bool, link: bool, v: bool }
      & DockerEngine::Internal::Type::request_parameters

    class ContainerDeleteParams < DockerEngine::Internal::Type::BaseModel
      extend DockerEngine::Internal::Type::RequestParameters::Converter
      include DockerEngine::Internal::Type::RequestParameters

      attr_reader force: bool?

      def force=: (bool) -> bool

      attr_reader link: bool?

      def link=: (bool) -> bool

      attr_reader v: bool?

      def v=: (bool) -> bool

      def initialize: (
        ?force: bool,
        ?link: bool,
        ?v: bool,
        ?request_options: DockerEngine::request_opts
      ) -> void

      def to_hash: -> {
        force: bool,
        link: bool,
        v: bool,
        request_options: DockerEngine::RequestOptions
      }
    end
  end
end
