module DockerEngine
  module Models
    type container_kill_params =
      { signal: String } & DockerEngine::Internal::Type::request_parameters

    class ContainerKillParams < DockerEngine::Internal::Type::BaseModel
      extend DockerEngine::Internal::Type::RequestParameters::Converter
      include DockerEngine::Internal::Type::RequestParameters

      attr_reader signal: String?

      def signal=: (String) -> String

      def initialize: (
        ?signal: String,
        ?request_options: DockerEngine::request_opts
      ) -> void

      def to_hash: -> {
        signal: String,
        request_options: DockerEngine::RequestOptions
      }
    end
  end
end
