module DockerEngine
  module Models
    type container_exec_response = { id: String }

    class ContainerExecResponse < DockerEngine::Internal::Type::BaseModel
      attr_accessor id: String

      def initialize: (id: String) -> void

      def to_hash: -> { id: String }
    end
  end
end
