module DockerEngine
  module Models
    type container_rename_params =
      { name: String } & DockerEngine::Internal::Type::request_parameters

    class ContainerRenameParams < DockerEngine::Internal::Type::BaseModel
      extend DockerEngine::Internal::Type::RequestParameters::Converter
      include DockerEngine::Internal::Type::RequestParameters

      attr_accessor name: String

      def initialize: (
        name: String,
        ?request_options: DockerEngine::request_opts
      ) -> void

      def to_hash: -> {
        name: String,
        request_options: DockerEngine::RequestOptions
      }
    end
  end
end
