module DockerEngine
  module Models
    type container_prune_params =
      { filters: String } & DockerEngine::Internal::Type::request_parameters

    class ContainerPruneParams < DockerEngine::Internal::Type::BaseModel
      extend DockerEngine::Internal::Type::RequestParameters::Converter
      include DockerEngine::Internal::Type::RequestParameters

      attr_reader filters: String?

      def filters=: (String) -> String

      def initialize: (
        ?filters: String,
        ?request_options: DockerEngine::request_opts
      ) -> void

      def to_hash: -> {
        filters: String,
        request_options: DockerEngine::RequestOptions
      }
    end
  end
end
