module DockerEngine
  module Models
    type container_start_params =
      { detach_keys: String } & DockerEngine::Internal::Type::request_parameters

    class ContainerStartParams < DockerEngine::Internal::Type::BaseModel
      extend DockerEngine::Internal::Type::RequestParameters::Converter
      include DockerEngine::Internal::Type::RequestParameters

      attr_reader detach_keys: String?

      def detach_keys=: (String) -> String

      def initialize: (
        ?detach_keys: String,
        ?request_options: DockerEngine::request_opts
      ) -> void

      def to_hash: -> {
        detach_keys: String,
        request_options: DockerEngine::RequestOptions
      }
    end
  end
end
