module DockerEngine
  module Models
    type container_top_params =
      { ps_args: String } & DockerEngine::Internal::Type::request_parameters

    class ContainerTopParams < DockerEngine::Internal::Type::BaseModel
      extend DockerEngine::Internal::Type::RequestParameters::Converter
      include DockerEngine::Internal::Type::RequestParameters

      attr_reader ps_args: String?

      def ps_args=: (String) -> String

      def initialize: (
        ?ps_args: String,
        ?request_options: DockerEngine::request_opts
      ) -> void

      def to_hash: -> {
        ps_args: String,
        request_options: DockerEngine::RequestOptions
      }
    end
  end
end
