module DockerEngine
  module Models
    type exec_inspect_params =
      {  } & DockerEngine::Internal::Type::request_parameters

    class ExecInspectParams < DockerEngine::Internal::Type::BaseModel
      extend DockerEngine::Internal::Type::RequestParameters::Converter
      include DockerEngine::Internal::Type::RequestParameters

      def initialize: (?request_options: DockerEngine::request_opts) -> void

      def to_hash: -> { request_options: DockerEngine::RequestOptions }
    end
  end
end
