module DockerEngine
  module Models
    type exec_resize_params =
      { h: Integer, w: Integer }
      & DockerEngine::Internal::Type::request_parameters

    class ExecResizeParams < DockerEngine::Internal::Type::BaseModel
      extend DockerEngine::Internal::Type::RequestParameters::Converter
      include DockerEngine::Internal::Type::RequestParameters

      attr_accessor h: Integer

      attr_accessor w: Integer

      def initialize: (
        h: Integer,
        w: Integer,
        ?request_options: DockerEngine::request_opts
      ) -> void

      def to_hash: -> {
        h: Integer,
        w: Integer,
        request_options: DockerEngine::RequestOptions
      }
    end
  end
end
