module DockerEngine
  module Models
    type image_get_params =
      { platform: ::Array[String] }
      & DockerEngine::Internal::Type::request_parameters

    class ImageGetParams < DockerEngine::Internal::Type::BaseModel
      extend DockerEngine::Internal::Type::RequestParameters::Converter
      include DockerEngine::Internal::Type::RequestParameters

      attr_reader platform: ::Array[String]?

      def platform=: (::Array[String]) -> ::Array[String]

      def initialize: (
        ?platform: ::Array[String],
        ?request_options: DockerEngine::request_opts
      ) -> void

      def to_hash: -> {
        platform: ::Array[String],
        request_options: DockerEngine::RequestOptions
      }
    end
  end
end
