module DockerEngine
  module Models
    type network_inspect_params =
      { scope: String, verbose: bool }
      & DockerEngine::Internal::Type::request_parameters

    class NetworkInspectParams < DockerEngine::Internal::Type::BaseModel
      extend DockerEngine::Internal::Type::RequestParameters::Converter
      include DockerEngine::Internal::Type::RequestParameters

      attr_reader scope: String?

      def scope=: (String) -> String

      attr_reader verbose: bool?

      def verbose=: (bool) -> bool

      def initialize: (
        ?scope: String,
        ?verbose: bool,
        ?request_options: DockerEngine::request_opts
      ) -> void

      def to_hash: -> {
        scope: String,
        verbose: bool,
        request_options: DockerEngine::RequestOptions
      }
    end
  end
end
