module DockerEngine
  module Models
    type plugin_set_params =
      { body: ::Array[String] }
      & DockerEngine::Internal::Type::request_parameters

    class PluginSetParams < DockerEngine::Internal::Type::BaseModel
      extend DockerEngine::Internal::Type::RequestParameters::Converter
      include DockerEngine::Internal::Type::RequestParameters

      attr_reader body: ::Array[String]?

      def body=: (::Array[String]) -> ::Array[String]

      def initialize: (
        ?body: ::Array[String],
        ?request_options: DockerEngine::request_opts
      ) -> void

      def to_hash: -> {
        body: ::Array[String],
        request_options: DockerEngine::RequestOptions
      }
    end
  end
end
