module DockerEngine
  module Models
    type secret_create_params =
      { spec: DockerEngine::SecretCreateParams::Spec }
      & DockerEngine::Internal::Type::request_parameters

    class SecretCreateParams < DockerEngine::Internal::Type::BaseModel
      extend DockerEngine::Internal::Type::RequestParameters::Converter
      include DockerEngine::Internal::Type::RequestParameters

      attr_reader spec: DockerEngine::SecretCreateParams::Spec?

      def spec=: (
        DockerEngine::SecretCreateParams::Spec
      ) -> DockerEngine::SecretCreateParams::Spec

      def initialize: (
        ?spec: DockerEngine::SecretCreateParams::Spec,
        ?request_options: DockerEngine::request_opts
      ) -> void

      def to_hash: -> {
        spec: DockerEngine::SecretCreateParams::Spec,
        request_options: DockerEngine::RequestOptions
      }

      type spec = {  }

      class Spec < DockerEngine::Models::Spec
        def initialize: -> void

        def to_hash: -> {  }
      end
    end
  end
end
