module DockerEngine
  module Models
    type service_inspect_params =
      { insert_defaults: bool }
      & DockerEngine::Internal::Type::request_parameters

    class ServiceInspectParams < DockerEngine::Internal::Type::BaseModel
      extend DockerEngine::Internal::Type::RequestParameters::Converter
      include DockerEngine::Internal::Type::RequestParameters

      attr_reader insert_defaults: bool?

      def insert_defaults=: (bool) -> bool

      def initialize: (
        ?insert_defaults: bool,
        ?request_options: DockerEngine::request_opts
      ) -> void

      def to_hash: -> {
        insert_defaults: bool,
        request_options: DockerEngine::RequestOptions
      }
    end
  end
end
