module DockerEngine
  module Models
    type service_create_response = { id: String, warnings: ::Array[String]? }

    class ServiceCreateResponse < DockerEngine::Internal::Type::BaseModel
      attr_reader id: String?

      def id=: (String) -> String

      attr_accessor warnings: ::Array[String]?

      def initialize: (?id: String, ?warnings: ::Array[String]?) -> void

      def to_hash: -> { id: String, warnings: ::Array[String]? }
    end
  end
end
