module DockerEngine
  module Models
    type service_create_params =
      { spec: DockerEngine::ServiceCreateParams::Spec, x_registry_auth: String }
      & DockerEngine::Internal::Type::request_parameters

    class ServiceCreateParams < DockerEngine::Internal::Type::BaseModel
      extend DockerEngine::Internal::Type::RequestParameters::Converter
      include DockerEngine::Internal::Type::RequestParameters

      attr_accessor spec: DockerEngine::ServiceCreateParams::Spec

      attr_reader x_registry_auth: String?

      def x_registry_auth=: (String) -> String

      def initialize: (
        spec: DockerEngine::ServiceCreateParams::Spec,
        ?x_registry_auth: String,
        ?request_options: DockerEngine::request_opts
      ) -> void

      def to_hash: -> {
        spec: DockerEngine::ServiceCreateParams::Spec,
        x_registry_auth: String,
        request_options: DockerEngine::RequestOptions
      }

      type spec = {  }

      class Spec < DockerEngine::Models::Spec
        def initialize: -> void

        def to_hash: -> {  }
      end
    end
  end
end
