module DockerEngine
  module Models
    type swarm_init_params =
      {
        advertise_addr: String,
        data_path_addr: String,
        data_path_port: Integer,
        default_addr_pool: ::Array[String],
        force_new_cluster: bool,
        listen_addr: String,
        spec: DockerEngine::Spec,
        subnet_size: Integer
      }
      & DockerEngine::Internal::Type::request_parameters

    class SwarmInitParams < DockerEngine::Internal::Type::BaseModel
      extend DockerEngine::Internal::Type::RequestParameters::Converter
      include DockerEngine::Internal::Type::RequestParameters

      attr_reader advertise_addr: String?

      def advertise_addr=: (String) -> String

      attr_reader data_path_addr: String?

      def data_path_addr=: (String) -> String

      attr_reader data_path_port: Integer?

      def data_path_port=: (Integer) -> Integer

      attr_reader default_addr_pool: ::Array[String]?

      def default_addr_pool=: (::Array[String]) -> ::Array[String]

      attr_reader force_new_cluster: bool?

      def force_new_cluster=: (bool) -> bool

      attr_reader listen_addr: String?

      def listen_addr=: (String) -> String

      attr_reader spec: DockerEngine::Spec?

      def spec=: (DockerEngine::Spec) -> DockerEngine::Spec

      attr_reader subnet_size: Integer?

      def subnet_size=: (Integer) -> Integer

      def initialize: (
        ?advertise_addr: String,
        ?data_path_addr: String,
        ?data_path_port: Integer,
        ?default_addr_pool: ::Array[String],
        ?force_new_cluster: bool,
        ?listen_addr: String,
        ?spec: DockerEngine::Spec,
        ?subnet_size: Integer,
        ?request_options: DockerEngine::request_opts
      ) -> void

      def to_hash: -> {
        advertise_addr: String,
        data_path_addr: String,
        data_path_port: Integer,
        default_addr_pool: ::Array[String],
        force_new_cluster: bool,
        listen_addr: String,
        spec: DockerEngine::Spec,
        subnet_size: Integer,
        request_options: DockerEngine::RequestOptions
      }
    end
  end
end
