module DockerEngine
  module Models
    type volume_update_params =
      { version: Integer, spec: DockerEngine::VolumeUpdateParams::Spec }
      & DockerEngine::Internal::Type::request_parameters

    class VolumeUpdateParams < DockerEngine::Internal::Type::BaseModel
      extend DockerEngine::Internal::Type::RequestParameters::Converter
      include DockerEngine::Internal::Type::RequestParameters

      attr_accessor version: Integer

      attr_reader spec: DockerEngine::VolumeUpdateParams::Spec?

      def spec=: (
        DockerEngine::VolumeUpdateParams::Spec
      ) -> DockerEngine::VolumeUpdateParams::Spec

      def initialize: (
        version: Integer,
        ?spec: DockerEngine::VolumeUpdateParams::Spec,
        ?request_options: DockerEngine::request_opts
      ) -> void

      def to_hash: -> {
        version: Integer,
        spec: DockerEngine::VolumeUpdateParams::Spec,
        request_options: DockerEngine::RequestOptions
      }

      type spec =
        {
          access_mode: DockerEngine::VolumeUpdateParams::Spec::AccessMode,
          group: String
        }

      class Spec < DockerEngine::Internal::Type::BaseModel
        attr_reader access_mode: DockerEngine::VolumeUpdateParams::Spec::AccessMode?

        def access_mode=: (
          DockerEngine::VolumeUpdateParams::Spec::AccessMode
        ) -> DockerEngine::VolumeUpdateParams::Spec::AccessMode

        attr_reader group: String?

        def group=: (String) -> String

        def initialize: (
          ?access_mode: DockerEngine::VolumeUpdateParams::Spec::AccessMode,
          ?group: String
        ) -> void

        def to_hash: -> {
          access_mode: DockerEngine::VolumeUpdateParams::Spec::AccessMode,
          group: String
        }

        type access_mode =
          {
            accessibility_requirements: DockerEngine::VolumeUpdateParams::Spec::AccessMode::AccessibilityRequirements,
            availability: DockerEngine::Models::VolumeUpdateParams::Spec::AccessMode::availability,
            capacity_range: DockerEngine::VolumeUpdateParams::Spec::AccessMode::CapacityRange,
            mount_volume: top,
            scope: DockerEngine::Models::VolumeUpdateParams::Spec::AccessMode::scope,
            secrets: ::Array[DockerEngine::VolumeUpdateParams::Spec::AccessMode::Secret],
            sharing: DockerEngine::Models::VolumeUpdateParams::Spec::AccessMode::sharing
          }

        class AccessMode < DockerEngine::Internal::Type::BaseModel
          attr_reader accessibility_requirements: DockerEngine::VolumeUpdateParams::Spec::AccessMode::AccessibilityRequirements?

          def accessibility_requirements=: (
            DockerEngine::VolumeUpdateParams::Spec::AccessMode::AccessibilityRequirements
          ) -> DockerEngine::VolumeUpdateParams::Spec::AccessMode::AccessibilityRequirements

          attr_reader availability: DockerEngine::Models::VolumeUpdateParams::Spec::AccessMode::availability?

          def availability=: (
            DockerEngine::Models::VolumeUpdateParams::Spec::AccessMode::availability
          ) -> DockerEngine::Models::VolumeUpdateParams::Spec::AccessMode::availability

          attr_reader capacity_range: DockerEngine::VolumeUpdateParams::Spec::AccessMode::CapacityRange?

          def capacity_range=: (
            DockerEngine::VolumeUpdateParams::Spec::AccessMode::CapacityRange
          ) -> DockerEngine::VolumeUpdateParams::Spec::AccessMode::CapacityRange

          attr_reader mount_volume: top?

          def mount_volume=: (top) -> top

          attr_reader scope: DockerEngine::Models::VolumeUpdateParams::Spec::AccessMode::scope?

          def scope=: (
            DockerEngine::Models::VolumeUpdateParams::Spec::AccessMode::scope
          ) -> DockerEngine::Models::VolumeUpdateParams::Spec::AccessMode::scope

          attr_reader secrets: ::Array[DockerEngine::VolumeUpdateParams::Spec::AccessMode::Secret]?

          def secrets=: (
            ::Array[DockerEngine::VolumeUpdateParams::Spec::AccessMode::Secret]
          ) -> ::Array[DockerEngine::VolumeUpdateParams::Spec::AccessMode::Secret]

          attr_reader sharing: DockerEngine::Models::VolumeUpdateParams::Spec::AccessMode::sharing?

          def sharing=: (
            DockerEngine::Models::VolumeUpdateParams::Spec::AccessMode::sharing
          ) -> DockerEngine::Models::VolumeUpdateParams::Spec::AccessMode::sharing

          def initialize: (
            ?accessibility_requirements: DockerEngine::VolumeUpdateParams::Spec::AccessMode::AccessibilityRequirements,
            ?availability: DockerEngine::Models::VolumeUpdateParams::Spec::AccessMode::availability,
            ?capacity_range: DockerEngine::VolumeUpdateParams::Spec::AccessMode::CapacityRange,
            ?mount_volume: top,
            ?scope: DockerEngine::Models::VolumeUpdateParams::Spec::AccessMode::scope,
            ?secrets: ::Array[DockerEngine::VolumeUpdateParams::Spec::AccessMode::Secret],
            ?sharing: DockerEngine::Models::VolumeUpdateParams::Spec::AccessMode::sharing
          ) -> void

          def to_hash: -> {
            accessibility_requirements: DockerEngine::VolumeUpdateParams::Spec::AccessMode::AccessibilityRequirements,
            availability: DockerEngine::Models::VolumeUpdateParams::Spec::AccessMode::availability,
            capacity_range: DockerEngine::VolumeUpdateParams::Spec::AccessMode::CapacityRange,
            mount_volume: top,
            scope: DockerEngine::Models::VolumeUpdateParams::Spec::AccessMode::scope,
            secrets: ::Array[DockerEngine::VolumeUpdateParams::Spec::AccessMode::Secret],
            sharing: DockerEngine::Models::VolumeUpdateParams::Spec::AccessMode::sharing
          }

          type accessibility_requirements =
            {
              preferred: ::Array[::Hash[Symbol, String]],
              requisite: ::Array[::Hash[Symbol, String]]
            }

          class AccessibilityRequirements < DockerEngine::Internal::Type::BaseModel
            attr_reader preferred: ::Array[::Hash[Symbol, String]]?

            def preferred=: (
              ::Array[::Hash[Symbol, String]]
            ) -> ::Array[::Hash[Symbol, String]]

            attr_reader requisite: ::Array[::Hash[Symbol, String]]?

            def requisite=: (
              ::Array[::Hash[Symbol, String]]
            ) -> ::Array[::Hash[Symbol, String]]

            def initialize: (
              ?preferred: ::Array[::Hash[Symbol, String]],
              ?requisite: ::Array[::Hash[Symbol, String]]
            ) -> void

            def to_hash: -> {
              preferred: ::Array[::Hash[Symbol, String]],
              requisite: ::Array[::Hash[Symbol, String]]
            }
          end

          type availability = :active | :pause | :drain

          module Availability
            extend DockerEngine::Internal::Type::Enum

            ACTIVE: :active
            PAUSE: :pause
            DRAIN: :drain

            def self?.values: -> ::Array[DockerEngine::Models::VolumeUpdateParams::Spec::AccessMode::availability]
          end

          type capacity_range =
            { limit_bytes: Integer, required_bytes: Integer }

          class CapacityRange < DockerEngine::Internal::Type::BaseModel
            attr_reader limit_bytes: Integer?

            def limit_bytes=: (Integer) -> Integer

            attr_reader required_bytes: Integer?

            def required_bytes=: (Integer) -> Integer

            def initialize: (
              ?limit_bytes: Integer,
              ?required_bytes: Integer
            ) -> void

            def to_hash: -> { limit_bytes: Integer, required_bytes: Integer }
          end

          type scope = :single | :multi

          module Scope
            extend DockerEngine::Internal::Type::Enum

            SINGLE: :single
            MULTI: :multi

            def self?.values: -> ::Array[DockerEngine::Models::VolumeUpdateParams::Spec::AccessMode::scope]
          end

          type secret = { key: String, secret: String }

          class Secret < DockerEngine::Internal::Type::BaseModel
            attr_reader key: String?

            def key=: (String) -> String

            attr_reader secret: String?

            def secret=: (String) -> String

            def initialize: (?key: String, ?secret: String) -> void

            def to_hash: -> { key: String, secret: String }
          end

          type sharing = :none | :readonly | :onewriter | :all

          module Sharing
            extend DockerEngine::Internal::Type::Enum

            NONE: :none
            READONLY: :readonly
            ONEWRITER: :onewriter
            ALL: :all

            def self?.values: -> ::Array[DockerEngine::Models::VolumeUpdateParams::Spec::AccessMode::sharing]
          end
        end
      end
    end
  end
end
