module DockerEngine
  module Models
    type volume_prune_response =
      { space_reclaimed: Integer, volumes_deleted: ::Array[String] }

    class VolumePruneResponse < DockerEngine::Internal::Type::BaseModel
      attr_reader space_reclaimed: Integer?

      def space_reclaimed=: (Integer) -> Integer

      attr_reader volumes_deleted: ::Array[String]?

      def volumes_deleted=: (::Array[String]) -> ::Array[String]

      def initialize: (
        ?space_reclaimed: Integer,
        ?volumes_deleted: ::Array[String]
      ) -> void

      def to_hash: -> {
        space_reclaimed: Integer,
        volumes_deleted: ::Array[String]
      }
    end
  end
end
