module DockerEngineRuby
  module Resources
    class Configs
      def create: (
        spec: DockerEngineRuby::ConfigSpec,
        ?request_options: DockerEngineRuby::request_opts
      ) -> DockerEngineRuby::Models::ConfigCreateResponse

      def update: (
        String id,
        version: Integer,
        spec: DockerEngineRuby::ConfigSpec,
        ?request_options: DockerEngineRuby::request_opts
      ) -> nil

      def list: (
        ?filters: String,
        ?request_options: DockerEngineRuby::request_opts
      ) -> DockerEngineRuby::Models::config_list_response

      def delete: (
        String id,
        ?request_options: DockerEngineRuby::request_opts
      ) -> nil

      def inspect_: (
        String id,
        ?request_options: DockerEngineRuby::request_opts
      ) -> DockerEngineRuby::ConfigObject

      def initialize: (client: DockerEngineRuby::Client) -> void
    end
  end
end
