module DockerEngineRuby
  module Resources
    class Images
      def list: (
        ?all: bool,
        ?digests: bool,
        ?filters: String,
        ?manifests: bool,
        ?shared_size: bool,
        ?request_options: DockerEngineRuby::request_opts
      ) -> DockerEngineRuby::Models::image_list_response

      def delete: (
        String name,
        ?force: bool,
        ?noprune: bool,
        ?platforms: ::Array[String],
        ?request_options: DockerEngineRuby::request_opts
      ) -> DockerEngineRuby::Models::image_delete_response

      def build: (
        body: top,
        ?buildargs: String,
        ?cachefrom: String,
        ?cpuperiod: Integer,
        ?cpuquota: Integer,
        ?cpusetcpus: String,
        ?cpushares: Integer,
        ?dockerfile: String,
        ?extrahosts: String,
        ?forcerm: bool,
        ?labels: String,
        ?memory: Integer,
        ?memswap: Integer,
        ?networkmode: String,
        ?nocache: bool,
        ?outputs: String,
        ?platform: String,
        ?pull: String,
        ?q: bool,
        ?remote: String,
        ?rm: bool,
        ?shmsize: Integer,
        ?squash: bool,
        ?t: String,
        ?target: String,
        ?version: DockerEngineRuby::Models::ImageBuildParams::version,
        ?x_registry_config: String,
        ?request_options: DockerEngineRuby::request_opts
      ) -> nil

      def build_prune: (
        ?all: bool,
        ?filters: String,
        ?max_used_space: Integer,
        ?min_free_space: Integer,
        ?reserved_space: Integer,
        ?request_options: DockerEngineRuby::request_opts
      ) -> DockerEngineRuby::Models::ImageBuildPruneResponse

      def commit: (
        ?author: String,
        ?changes: String,
        ?comment: String,
        ?container: String,
        ?pause: bool,
        ?repo: String,
        ?tag: String,
        ?args_escaped: bool?,
        ?attach_stderr: bool,
        ?attach_stdin: bool,
        ?attach_stdout: bool,
        ?cmd: ::Array[String],
        ?domainname: String,
        ?entrypoint: ::Array[String],
        ?env: ::Array[String],
        ?exposed_ports: top?,
        ?healthcheck: DockerEngineRuby::Config::Healthcheck,
        ?hostname: String,
        ?image: String,
        ?labels: top,
        ?network_disabled: bool?,
        ?on_build: ::Array[String]?,
        ?open_stdin: bool,
        ?shell: ::Array[String]?,
        ?stdin_once: bool,
        ?stop_signal: String?,
        ?stop_timeout: Integer?,
        ?tty: bool,
        ?user: String,
        ?volumes: top,
        ?working_dir: String,
        ?request_options: DockerEngineRuby::request_opts
      ) -> DockerEngineRuby::Models::ImageCommitResponse

      def get: (
        String name,
        ?platform: ::Array[String],
        ?request_options: DockerEngineRuby::request_opts
      ) -> StringIO

      def get_all: (
        ?names: ::Array[String],
        ?platform: ::Array[String],
        ?request_options: DockerEngineRuby::request_opts
      ) -> StringIO

      def history: (
        String name,
        ?platform: String,
        ?request_options: DockerEngineRuby::request_opts
      ) -> DockerEngineRuby::Models::image_history_response

      def inspect_: (
        String name,
        ?manifests: bool,
        ?request_options: DockerEngineRuby::request_opts
      ) -> DockerEngineRuby::Image

      def load_: (
        body: top,
        ?platform: ::Array[String],
        ?quiet: bool,
        ?request_options: DockerEngineRuby::request_opts
      ) -> nil

      def prune: (
        ?filters: String,
        ?request_options: DockerEngineRuby::request_opts
      ) -> DockerEngineRuby::Models::ImagePruneResponse

      def pull: (
        body: String,
        ?changes: ::Array[String],
        ?from_image: String,
        ?from_src: String,
        ?message: String,
        ?platform: String,
        ?repo: String,
        ?tag: String,
        ?x_registry_auth: String,
        ?request_options: DockerEngineRuby::request_opts
      ) -> nil

      def push: (
        String name,
        x_registry_auth: String,
        ?platform: String,
        ?tag: String,
        ?request_options: DockerEngineRuby::request_opts
      ) -> nil

      def search: (
        term: String,
        ?filters: String,
        ?limit: Integer,
        ?request_options: DockerEngineRuby::request_opts
      ) -> DockerEngineRuby::Models::image_search_response

      def tag: (
        String name,
        ?repo: String,
        ?tag: String,
        ?request_options: DockerEngineRuby::request_opts
      ) -> nil

      def initialize: (client: DockerEngineRuby::Client) -> void
    end
  end
end
