module DockerEngineRuby
  module Resources
    class Networks
      def create: (
        name: String,
        ?attachable: bool,
        ?config_from: DockerEngineRuby::NetworkCreateParams::ConfigFrom,
        ?config_only: bool,
        ?driver: String,
        ?enable_i_pv4: bool,
        ?enable_i_pv6: bool,
        ?ingress: bool,
        ?internal: bool,
        ?ipam: DockerEngineRuby::NetworkCreateParams::Ipam,
        ?labels: ::Hash[Symbol, String],
        ?options: ::Hash[Symbol, String],
        ?scope: String,
        ?request_options: DockerEngineRuby::request_opts
      ) -> DockerEngineRuby::CreateResponse

      def list: (
        ?filters: String,
        ?request_options: DockerEngineRuby::request_opts
      ) -> DockerEngineRuby::Models::network_list_response

      def delete: (
        String id,
        ?request_options: DockerEngineRuby::request_opts
      ) -> nil

      def connect: (
        String id,
        container: String,
        ?endpoint_config: DockerEngineRuby::ConnectRequest::EndpointConfig,
        ?request_options: DockerEngineRuby::request_opts
      ) -> nil

      def disconnect: (
        String id,
        container: String,
        ?force: bool,
        ?request_options: DockerEngineRuby::request_opts
      ) -> nil

      def inspect_: (
        String id,
        ?scope: String,
        ?verbose: bool,
        ?request_options: DockerEngineRuby::request_opts
      ) -> DockerEngineRuby::Models::NetworkInspectResponse

      def prune: (
        ?filters: String,
        ?request_options: DockerEngineRuby::request_opts
      ) -> DockerEngineRuby::Models::NetworkPruneResponse

      def initialize: (client: DockerEngineRuby::Client) -> void
    end
  end
end
