module DockerEngineRuby
  module Resources
    class Nodes
      def update: (
        String id,
        version: Integer,
        spec: DockerEngineRuby::Spec,
        ?request_options: DockerEngineRuby::request_opts
      ) -> nil

      def list: (
        ?filters: String,
        ?request_options: DockerEngineRuby::request_opts
      ) -> DockerEngineRuby::Models::node_list_response

      def delete: (
        String id,
        ?force: bool,
        ?request_options: DockerEngineRuby::request_opts
      ) -> nil

      def inspect_: (
        String id,
        ?request_options: DockerEngineRuby::request_opts
      ) -> DockerEngineRuby::Node

      def initialize: (client: DockerEngineRuby::Client) -> void
    end
  end
end
