module DockerEngineRuby
  module Resources
    class Secrets
      def create: (
        ?spec: DockerEngineRuby::SecretCreateParams::Spec,
        ?request_options: DockerEngineRuby::request_opts
      ) -> DockerEngineRuby::Models::SecretCreateResponse

      def update: (
        String id,
        version: Integer,
        ?spec: DockerEngineRuby::Spec,
        ?request_options: DockerEngineRuby::request_opts
      ) -> nil

      def list: (
        ?filters: String,
        ?request_options: DockerEngineRuby::request_opts
      ) -> DockerEngineRuby::Models::secret_list_response

      def delete: (
        String id,
        ?request_options: DockerEngineRuby::request_opts
      ) -> nil

      def inspect_: (
        String id,
        ?request_options: DockerEngineRuby::request_opts
      ) -> DockerEngineRuby::Secret

      def initialize: (client: DockerEngineRuby::Client) -> void
    end
  end
end
