module DockerEngineRuby
  module Resources
    class Services
      def create: (
        spec: DockerEngineRuby::Spec,
        ?x_registry_auth: String,
        ?request_options: DockerEngineRuby::request_opts
      ) -> DockerEngineRuby::CreateResponse

      def update: (
        String id,
        version: Integer,
        spec: DockerEngineRuby::Spec,
        ?registry_auth_from: DockerEngineRuby::Models::ServiceUpdateParams::registry_auth_from,
        ?rollback: String,
        ?x_registry_auth: String,
        ?request_options: DockerEngineRuby::request_opts
      ) -> DockerEngineRuby::UpdateResponse

      def list: (
        ?filters: String,
        ?status: bool,
        ?request_options: DockerEngineRuby::request_opts
      ) -> DockerEngineRuby::Models::service_list_response

      def delete: (
        String id,
        ?request_options: DockerEngineRuby::request_opts
      ) -> nil

      def inspect_: (
        String id,
        ?insert_defaults: bool,
        ?request_options: DockerEngineRuby::request_opts
      ) -> DockerEngineRuby::Service

      def logs: (
        String id,
        ?details: bool,
        ?follow: bool,
        ?since: Integer,
        ?stderr: bool,
        ?stdout: bool,
        ?tail: String,
        ?timestamps: bool,
        ?request_options: DockerEngineRuby::request_opts
      ) -> StringIO

      def initialize: (client: DockerEngineRuby::Client) -> void
    end
  end
end
