module DockerEngineAPI
  class Client < DockerEngineAPI::Internal::Transport::BaseClient
    DEFAULT_MAX_RETRIES: 2

    DEFAULT_TIMEOUT_IN_SECONDS: Float

    DEFAULT_INITIAL_RETRY_DELAY: Float

    DEFAULT_MAX_RETRY_DELAY: Float

    attr_reader auth: DockerEngineAPI::Resources::Auth

    attr_reader system_: DockerEngineAPI::Resources::System

    attr_reader containers: DockerEngineAPI::Resources::Containers

    attr_reader exec_: DockerEngineAPI::Resources::Exec

    attr_reader images: DockerEngineAPI::Resources::Images

    attr_reader networks: DockerEngineAPI::Resources::Networks

    attr_reader volumes: DockerEngineAPI::Resources::Volumes

    attr_reader services: DockerEngineAPI::Resources::Services

    attr_reader configs: DockerEngineAPI::Resources::Configs

    attr_reader secrets: DockerEngineAPI::Resources::Secrets

    attr_reader nodes: DockerEngineAPI::Resources::Nodes

    attr_reader swarm: DockerEngineAPI::Resources::Swarm

    attr_reader tasks: DockerEngineAPI::Resources::Tasks

    attr_reader plugins: DockerEngineAPI::Resources::Plugins

    attr_reader distribution: DockerEngineAPI::Resources::Distribution

    def initialize: (
      ?base_url: String?,
      ?max_retries: Integer,
      ?timeout: Float,
      ?initial_retry_delay: Float,
      ?max_retry_delay: Float
    ) -> void
  end
end
