module DockerEngineAPI
  class AuthLoginParams = DockerEngineAPI::Models::AuthLoginParams

  class AuthResponse = DockerEngineAPI::Models::AuthResponse

  class Config = DockerEngineAPI::Models::Config

  class ConfigCreateParams = DockerEngineAPI::Models::ConfigCreateParams

  class ConfigDeleteParams = DockerEngineAPI::Models::ConfigDeleteParams

  class ConfigInspectParams = DockerEngineAPI::Models::ConfigInspectParams

  class ConfigListParams = DockerEngineAPI::Models::ConfigListParams

  class ConfigUpdateParams = DockerEngineAPI::Models::ConfigUpdateParams

  class ConnectRequest = DockerEngineAPI::Models::ConnectRequest

  class Container = DockerEngineAPI::Models::Container

  class ContainerArchiveParams = DockerEngineAPI::Models::ContainerArchiveParams

  class ContainerAttachParams = DockerEngineAPI::Models::ContainerAttachParams

  class ContainerChangesParams = DockerEngineAPI::Models::ContainerChangesParams

  class ContainerCreateParams = DockerEngineAPI::Models::ContainerCreateParams

  class ContainerDeleteParams = DockerEngineAPI::Models::ContainerDeleteParams

  class ContainerExecParams = DockerEngineAPI::Models::ContainerExecParams

  class ContainerExportParams = DockerEngineAPI::Models::ContainerExportParams

  class ContainerInspectParams = DockerEngineAPI::Models::ContainerInspectParams

  class ContainerKillParams = DockerEngineAPI::Models::ContainerKillParams

  class ContainerListParams = DockerEngineAPI::Models::ContainerListParams

  class ContainerLogsParams = DockerEngineAPI::Models::ContainerLogsParams

  class ContainerPauseParams = DockerEngineAPI::Models::ContainerPauseParams

  class ContainerPruneParams = DockerEngineAPI::Models::ContainerPruneParams

  class ContainerRenameParams = DockerEngineAPI::Models::ContainerRenameParams

  class ContainerResizeParams = DockerEngineAPI::Models::ContainerResizeParams

  class ContainerRestartParams = DockerEngineAPI::Models::ContainerRestartParams

  class ContainerStartParams = DockerEngineAPI::Models::ContainerStartParams

  class ContainerStatsParams = DockerEngineAPI::Models::ContainerStatsParams

  class ContainerStopParams = DockerEngineAPI::Models::ContainerStopParams

  class ContainerTopParams = DockerEngineAPI::Models::ContainerTopParams

  class ContainerUnpauseParams = DockerEngineAPI::Models::ContainerUnpauseParams

  class ContainerUpdateParams = DockerEngineAPI::Models::ContainerUpdateParams

  class ContainerWaitParams = DockerEngineAPI::Models::ContainerWaitParams

  class CreateRequest = DockerEngineAPI::Models::CreateRequest

  class CreateResponse = DockerEngineAPI::Models::CreateResponse

  class DeleteItem = DockerEngineAPI::Models::DeleteItem

  class DisconnectRequest = DockerEngineAPI::Models::DisconnectRequest

  class DistributionInspectParams = DockerEngineAPI::Models::DistributionInspectParams

  class Error = DockerEngineAPI::Models::Error

  class ExecInspectParams = DockerEngineAPI::Models::ExecInspectParams

  class ExecResizeParams = DockerEngineAPI::Models::ExecResizeParams

  class ExecStartParams = DockerEngineAPI::Models::ExecStartParams

  class FilesystemChange = DockerEngineAPI::Models::FilesystemChange

  class HistoryItem = DockerEngineAPI::Models::HistoryItem

  class Image = DockerEngineAPI::Models::Image

  class ImageBuildParams = DockerEngineAPI::Models::ImageBuildParams

  class ImageBuildPruneParams = DockerEngineAPI::Models::ImageBuildPruneParams

  class ImageCommitParams = DockerEngineAPI::Models::ImageCommitParams

  class ImageDeleteParams = DockerEngineAPI::Models::ImageDeleteParams

  class ImageGetAllParams = DockerEngineAPI::Models::ImageGetAllParams

  class ImageGetParams = DockerEngineAPI::Models::ImageGetParams

  class ImageHistoryParams = DockerEngineAPI::Models::ImageHistoryParams

  class ImageInspectParams = DockerEngineAPI::Models::ImageInspectParams

  class ImageListParams = DockerEngineAPI::Models::ImageListParams

  class ImageLoadParams = DockerEngineAPI::Models::ImageLoadParams

  class ImagePruneParams = DockerEngineAPI::Models::ImagePruneParams

  class ImagePullParams = DockerEngineAPI::Models::ImagePullParams

  class ImagePushParams = DockerEngineAPI::Models::ImagePushParams

  class ImageSearchParams = DockerEngineAPI::Models::ImageSearchParams

  class ImageTagParams = DockerEngineAPI::Models::ImageTagParams

  class Info = DockerEngineAPI::Models::Info

  class Inspect = DockerEngineAPI::Models::Inspect

  class InspectResponse = DockerEngineAPI::Models::InspectResponse

  class ListResponse = DockerEngineAPI::Models::ListResponse

  class Network = DockerEngineAPI::Models::Network

  class NetworkConnectParams = DockerEngineAPI::Models::NetworkConnectParams

  class NetworkCreateParams = DockerEngineAPI::Models::NetworkCreateParams

  class NetworkDeleteParams = DockerEngineAPI::Models::NetworkDeleteParams

  class NetworkDisconnectParams = DockerEngineAPI::Models::NetworkDisconnectParams

  class NetworkInspectParams = DockerEngineAPI::Models::NetworkInspectParams

  class NetworkListParams = DockerEngineAPI::Models::NetworkListParams

  class NetworkPruneParams = DockerEngineAPI::Models::NetworkPruneParams

  class Node = DockerEngineAPI::Models::Node

  class NodeDeleteParams = DockerEngineAPI::Models::NodeDeleteParams

  class NodeInspectParams = DockerEngineAPI::Models::NodeInspectParams

  class NodeListParams = DockerEngineAPI::Models::NodeListParams

  class NodeUpdateParams = DockerEngineAPI::Models::NodeUpdateParams

  class Plugin = DockerEngineAPI::Models::Plugin

  class PluginCreateParams = DockerEngineAPI::Models::PluginCreateParams

  class PluginDeleteParams = DockerEngineAPI::Models::PluginDeleteParams

  class PluginDisableParams = DockerEngineAPI::Models::PluginDisableParams

  class PluginEnableParams = DockerEngineAPI::Models::PluginEnableParams

  class PluginInspectParams = DockerEngineAPI::Models::PluginInspectParams

  class PluginListParams = DockerEngineAPI::Models::PluginListParams

  class PluginPrivilegesParams = DockerEngineAPI::Models::PluginPrivilegesParams

  class PluginPullParams = DockerEngineAPI::Models::PluginPullParams

  class PluginPushParams = DockerEngineAPI::Models::PluginPushParams

  class PluginSetParams = DockerEngineAPI::Models::PluginSetParams

  class PluginUpgradeParams = DockerEngineAPI::Models::PluginUpgradeParams

  class Privilege = DockerEngineAPI::Models::Privilege

  class Secret = DockerEngineAPI::Models::Secret

  class SecretCreateParams = DockerEngineAPI::Models::SecretCreateParams

  class SecretDeleteParams = DockerEngineAPI::Models::SecretDeleteParams

  class SecretInspectParams = DockerEngineAPI::Models::SecretInspectParams

  class SecretListParams = DockerEngineAPI::Models::SecretListParams

  class SecretUpdateParams = DockerEngineAPI::Models::SecretUpdateParams

  class Service = DockerEngineAPI::Models::Service

  class ServiceCreateParams = DockerEngineAPI::Models::ServiceCreateParams

  class ServiceDeleteParams = DockerEngineAPI::Models::ServiceDeleteParams

  class ServiceInspectParams = DockerEngineAPI::Models::ServiceInspectParams

  class ServiceListParams = DockerEngineAPI::Models::ServiceListParams

  class ServiceLogsParams = DockerEngineAPI::Models::ServiceLogsParams

  class ServiceUpdateParams = DockerEngineAPI::Models::ServiceUpdateParams

  class Spec = DockerEngineAPI::Models::Spec

  class StatsResponse = DockerEngineAPI::Models::StatsResponse

  class Summary = DockerEngineAPI::Models::Summary

  class SwarmAPI = DockerEngineAPI::Models::SwarmAPI

  class SwarmInitParams = DockerEngineAPI::Models::SwarmInitParams

  class SwarmInspectParams = DockerEngineAPI::Models::SwarmInspectParams

  class SwarmJoinParams = DockerEngineAPI::Models::SwarmJoinParams

  class SwarmLeaveParams = DockerEngineAPI::Models::SwarmLeaveParams

  class SwarmUnlockKeyParams = DockerEngineAPI::Models::SwarmUnlockKeyParams

  class SwarmUnlockParams = DockerEngineAPI::Models::SwarmUnlockParams

  class SwarmUpdateParams = DockerEngineAPI::Models::SwarmUpdateParams

  class SystemDataUsageParams = DockerEngineAPI::Models::SystemDataUsageParams

  class SystemEventsParams = DockerEngineAPI::Models::SystemEventsParams

  class SystemInfoParams = DockerEngineAPI::Models::SystemInfoParams

  class SystemPingParams = DockerEngineAPI::Models::SystemPingParams

  class SystemVersionParams = DockerEngineAPI::Models::SystemVersionParams

  class Task = DockerEngineAPI::Models::Task

  class TaskInspectParams = DockerEngineAPI::Models::TaskInspectParams

  class TaskListParams = DockerEngineAPI::Models::TaskListParams

  class TaskLogsParams = DockerEngineAPI::Models::TaskLogsParams

  class TopResponse = DockerEngineAPI::Models::TopResponse

  class UpdateResponse = DockerEngineAPI::Models::UpdateResponse

  class Version = DockerEngineAPI::Models::Version

  class Volume = DockerEngineAPI::Models::Volume

  class VolumeCreateParams = DockerEngineAPI::Models::VolumeCreateParams

  class VolumeDeleteParams = DockerEngineAPI::Models::VolumeDeleteParams

  class VolumeInspectParams = DockerEngineAPI::Models::VolumeInspectParams

  class VolumeListParams = DockerEngineAPI::Models::VolumeListParams

  class VolumePruneParams = DockerEngineAPI::Models::VolumePruneParams

  class VolumeUpdateParams = DockerEngineAPI::Models::VolumeUpdateParams

  class WaitResponse = DockerEngineAPI::Models::WaitResponse
end
