module DockerEngine
  class Client < DockerEngine::Internal::Transport::BaseClient
    DEFAULT_MAX_RETRIES: 2

    DEFAULT_TIMEOUT_IN_SECONDS: Float

    DEFAULT_INITIAL_RETRY_DELAY: Float

    DEFAULT_MAX_RETRY_DELAY: Float

    attr_reader auth: DockerEngine::Resources::Auth

    attr_reader system_: DockerEngine::Resources::System

    attr_reader containers: DockerEngine::Resources::Containers

    attr_reader exec_: DockerEngine::Resources::Exec

    attr_reader images: DockerEngine::Resources::Images

    attr_reader networks: DockerEngine::Resources::Networks

    attr_reader volumes: DockerEngine::Resources::Volumes

    attr_reader services: DockerEngine::Resources::Services

    attr_reader configs: DockerEngine::Resources::Configs

    attr_reader secrets: DockerEngine::Resources::Secrets

    attr_reader nodes: DockerEngine::Resources::Nodes

    attr_reader swarm: DockerEngine::Resources::Swarm

    attr_reader tasks: DockerEngine::Resources::Tasks

    attr_reader plugins: DockerEngine::Resources::Plugins

    attr_reader distribution: DockerEngine::Resources::Distribution

    def initialize: (
      ?base_url: String?,
      ?max_retries: Integer,
      ?timeout: Float,
      ?initial_retry_delay: Float,
      ?max_retry_delay: Float
    ) -> void
  end
end
