module DockerEngine
  class AuthLoginParams = DockerEngine::Models::AuthLoginParams

  class AuthResponse = DockerEngine::Models::AuthResponse

  class Config = DockerEngine::Models::Config

  class ConfigCreateParams = DockerEngine::Models::ConfigCreateParams

  class ConfigDeleteParams = DockerEngine::Models::ConfigDeleteParams

  class ConfigInspectParams = DockerEngine::Models::ConfigInspectParams

  class ConfigListParams = DockerEngine::Models::ConfigListParams

  class ConfigUpdateParams = DockerEngine::Models::ConfigUpdateParams

  class ConnectRequest = DockerEngine::Models::ConnectRequest

  class Container = DockerEngine::Models::Container

  class ContainerArchiveParams = DockerEngine::Models::ContainerArchiveParams

  class ContainerAttachParams = DockerEngine::Models::ContainerAttachParams

  class ContainerChangesParams = DockerEngine::Models::ContainerChangesParams

  class ContainerCreateParams = DockerEngine::Models::ContainerCreateParams

  class ContainerDeleteParams = DockerEngine::Models::ContainerDeleteParams

  class ContainerExecParams = DockerEngine::Models::ContainerExecParams

  class ContainerExportParams = DockerEngine::Models::ContainerExportParams

  class ContainerInspectParams = DockerEngine::Models::ContainerInspectParams

  class ContainerKillParams = DockerEngine::Models::ContainerKillParams

  class ContainerListParams = DockerEngine::Models::ContainerListParams

  class ContainerLogsParams = DockerEngine::Models::ContainerLogsParams

  class ContainerPauseParams = DockerEngine::Models::ContainerPauseParams

  class ContainerPruneParams = DockerEngine::Models::ContainerPruneParams

  class ContainerRenameParams = DockerEngine::Models::ContainerRenameParams

  class ContainerResizeParams = DockerEngine::Models::ContainerResizeParams

  class ContainerRestartParams = DockerEngine::Models::ContainerRestartParams

  class ContainerStartParams = DockerEngine::Models::ContainerStartParams

  class ContainerStatsParams = DockerEngine::Models::ContainerStatsParams

  class ContainerStopParams = DockerEngine::Models::ContainerStopParams

  class ContainerTopParams = DockerEngine::Models::ContainerTopParams

  class ContainerUnpauseParams = DockerEngine::Models::ContainerUnpauseParams

  class ContainerUpdateParams = DockerEngine::Models::ContainerUpdateParams

  class ContainerWaitParams = DockerEngine::Models::ContainerWaitParams

  class CreateRequest = DockerEngine::Models::CreateRequest

  class CreateResponse = DockerEngine::Models::CreateResponse

  class DeleteItem = DockerEngine::Models::DeleteItem

  class DisconnectRequest = DockerEngine::Models::DisconnectRequest

  class DistributionInspectParams = DockerEngine::Models::DistributionInspectParams

  class Error = DockerEngine::Models::Error

  class ExecInspectParams = DockerEngine::Models::ExecInspectParams

  class ExecResizeParams = DockerEngine::Models::ExecResizeParams

  class ExecStartParams = DockerEngine::Models::ExecStartParams

  class FilesystemChange = DockerEngine::Models::FilesystemChange

  class HistoryItem = DockerEngine::Models::HistoryItem

  class Image = DockerEngine::Models::Image

  class ImageBuildParams = DockerEngine::Models::ImageBuildParams

  class ImageBuildPruneParams = DockerEngine::Models::ImageBuildPruneParams

  class ImageCommitParams = DockerEngine::Models::ImageCommitParams

  class ImageDeleteParams = DockerEngine::Models::ImageDeleteParams

  class ImageGetAllParams = DockerEngine::Models::ImageGetAllParams

  class ImageGetParams = DockerEngine::Models::ImageGetParams

  class ImageHistoryParams = DockerEngine::Models::ImageHistoryParams

  class ImageInspectParams = DockerEngine::Models::ImageInspectParams

  class ImageListParams = DockerEngine::Models::ImageListParams

  class ImageLoadParams = DockerEngine::Models::ImageLoadParams

  class ImagePruneParams = DockerEngine::Models::ImagePruneParams

  class ImagePullParams = DockerEngine::Models::ImagePullParams

  class ImagePushParams = DockerEngine::Models::ImagePushParams

  class ImageSearchParams = DockerEngine::Models::ImageSearchParams

  class ImageTagParams = DockerEngine::Models::ImageTagParams

  class Info = DockerEngine::Models::Info

  class Inspect = DockerEngine::Models::Inspect

  class InspectResponse = DockerEngine::Models::InspectResponse

  class ListResponse = DockerEngine::Models::ListResponse

  class Network = DockerEngine::Models::Network

  class NetworkConnectParams = DockerEngine::Models::NetworkConnectParams

  class NetworkCreateParams = DockerEngine::Models::NetworkCreateParams

  class NetworkDeleteParams = DockerEngine::Models::NetworkDeleteParams

  class NetworkDisconnectParams = DockerEngine::Models::NetworkDisconnectParams

  class NetworkInspectParams = DockerEngine::Models::NetworkInspectParams

  class NetworkListParams = DockerEngine::Models::NetworkListParams

  class NetworkPruneParams = DockerEngine::Models::NetworkPruneParams

  class Node = DockerEngine::Models::Node

  class NodeDeleteParams = DockerEngine::Models::NodeDeleteParams

  class NodeInspectParams = DockerEngine::Models::NodeInspectParams

  class NodeListParams = DockerEngine::Models::NodeListParams

  class NodeUpdateParams = DockerEngine::Models::NodeUpdateParams

  class Plugin = DockerEngine::Models::Plugin

  class PluginCreateParams = DockerEngine::Models::PluginCreateParams

  class PluginDeleteParams = DockerEngine::Models::PluginDeleteParams

  class PluginDisableParams = DockerEngine::Models::PluginDisableParams

  class PluginEnableParams = DockerEngine::Models::PluginEnableParams

  class PluginInspectParams = DockerEngine::Models::PluginInspectParams

  class PluginListParams = DockerEngine::Models::PluginListParams

  class PluginPrivilegesParams = DockerEngine::Models::PluginPrivilegesParams

  class PluginPullParams = DockerEngine::Models::PluginPullParams

  class PluginPushParams = DockerEngine::Models::PluginPushParams

  class PluginSetParams = DockerEngine::Models::PluginSetParams

  class PluginUpgradeParams = DockerEngine::Models::PluginUpgradeParams

  class Privilege = DockerEngine::Models::Privilege

  class Secret = DockerEngine::Models::Secret

  class SecretCreateParams = DockerEngine::Models::SecretCreateParams

  class SecretDeleteParams = DockerEngine::Models::SecretDeleteParams

  class SecretInspectParams = DockerEngine::Models::SecretInspectParams

  class SecretListParams = DockerEngine::Models::SecretListParams

  class SecretUpdateParams = DockerEngine::Models::SecretUpdateParams

  class Service = DockerEngine::Models::Service

  class ServiceCreateParams = DockerEngine::Models::ServiceCreateParams

  class ServiceDeleteParams = DockerEngine::Models::ServiceDeleteParams

  class ServiceInspectParams = DockerEngine::Models::ServiceInspectParams

  class ServiceListParams = DockerEngine::Models::ServiceListParams

  class ServiceLogsParams = DockerEngine::Models::ServiceLogsParams

  class ServiceUpdateParams = DockerEngine::Models::ServiceUpdateParams

  class Spec = DockerEngine::Models::Spec

  class StatsResponse = DockerEngine::Models::StatsResponse

  class Summary = DockerEngine::Models::Summary

  class SwarmAPI = DockerEngine::Models::SwarmAPI

  class SwarmInitParams = DockerEngine::Models::SwarmInitParams

  class SwarmInspectParams = DockerEngine::Models::SwarmInspectParams

  class SwarmJoinParams = DockerEngine::Models::SwarmJoinParams

  class SwarmLeaveParams = DockerEngine::Models::SwarmLeaveParams

  class SwarmUnlockKeyParams = DockerEngine::Models::SwarmUnlockKeyParams

  class SwarmUnlockParams = DockerEngine::Models::SwarmUnlockParams

  class SwarmUpdateParams = DockerEngine::Models::SwarmUpdateParams

  class SystemDataUsageParams = DockerEngine::Models::SystemDataUsageParams

  class SystemEventsParams = DockerEngine::Models::SystemEventsParams

  class SystemInfoParams = DockerEngine::Models::SystemInfoParams

  class SystemPingParams = DockerEngine::Models::SystemPingParams

  class SystemVersionParams = DockerEngine::Models::SystemVersionParams

  class Task = DockerEngine::Models::Task

  class TaskInspectParams = DockerEngine::Models::TaskInspectParams

  class TaskListParams = DockerEngine::Models::TaskListParams

  class TaskLogsParams = DockerEngine::Models::TaskLogsParams

  class TopResponse = DockerEngine::Models::TopResponse

  class UpdateResponse = DockerEngine::Models::UpdateResponse

  class Version = DockerEngine::Models::Version

  class Volume = DockerEngine::Models::Volume

  class VolumeCreateParams = DockerEngine::Models::VolumeCreateParams

  class VolumeDeleteParams = DockerEngine::Models::VolumeDeleteParams

  class VolumeInspectParams = DockerEngine::Models::VolumeInspectParams

  class VolumeListParams = DockerEngine::Models::VolumeListParams

  class VolumePruneParams = DockerEngine::Models::VolumePruneParams

  class VolumeUpdateParams = DockerEngine::Models::VolumeUpdateParams

  class WaitResponse = DockerEngine::Models::WaitResponse
end
