module DockerEngineAPI
  module Resources
    class Auth
      def login: (
        ?password: String,
        ?serveraddress: String,
        ?username: String,
        ?request_options: DockerEngineAPI::request_opts
      ) -> DockerEngineAPI::AuthResponse

      def initialize: (client: DockerEngineAPI::Client) -> void
    end
  end
end
