module DockerEngineAPI
  module Resources
    class Distribution
      def inspect_: (
        String name,
        ?request_options: DockerEngineAPI::request_opts
      ) -> DockerEngineAPI::Inspect

      def initialize: (client: DockerEngineAPI::Client) -> void
    end
  end
end
