module DockerEngineAPI
  module Resources
    class System
      def data_usage: (
        ?type: ::Array[DockerEngineAPI::Models::SystemDataUsageParams::type_],
        ?verbose: bool,
        ?request_options: DockerEngineAPI::request_opts
      ) -> DockerEngineAPI::Models::SystemDataUsageResponse

      def events: (
        ?filters: String,
        ?since: String,
        ?until_: String,
        ?request_options: DockerEngineAPI::request_opts
      ) -> DockerEngineAPI::Models::SystemEventsResponse

      def info: (
        ?request_options: DockerEngineAPI::request_opts
      ) -> DockerEngineAPI::Info

      def ping: (?request_options: DockerEngineAPI::request_opts) -> String

      def version: (
        ?request_options: DockerEngineAPI::request_opts
      ) -> DockerEngineAPI::Version

      def initialize: (client: DockerEngineAPI::Client) -> void
    end
  end
end
