module DockerEngineRuby
  module Internal
    module Transport
      class PooledNetRequester
        extend DockerEngineRuby::Internal::Util::SorbetRuntimeSupport

        type request =
          {
            method: Symbol,
            url: URI::Generic,
            headers: ::Hash[String, String],
            body: top,
            deadline: Float
          }

        KEEP_ALIVE_TIMEOUT: 30

        DEFAULT_MAX_CONNECTIONS: Integer

        def self.connect: (
          cert_store: OpenSSL::X509::Store,
          tls_cert: OpenSSL::X509::Certificate?,
          tls_key: OpenSSL::PKey::PKey?,
          tls_verify_peer: bool,
          url: URI::Generic
        ) -> top

        def self.calibrate_socket_timeout: (top conn, Float deadline) -> void

        def self.build_request: (
          DockerEngineRuby::Internal::Transport::PooledNetRequester::request request
        ) {
          (String arg0) -> void
        } -> [top, (^-> void)]

        private def with_pool: (
          URI::Generic url,
          deadline: Float
        ) {
          (top arg0) -> void
        } -> void

        def execute: (
          DockerEngineRuby::Internal::Transport::PooledNetRequester::request request
        ) -> [Integer, top, Enumerable[String]]

        def initialize: (
          ?size: Integer,
          ?tls_verify_peer: bool,
          ?tls_ca_cert_path: String?,
          ?tls_client_cert_path: String?,
          ?tls_client_key_path: String?
        ) -> void
      end
    end
  end
end
