module DockerEngineRuby
  module Models
    type config_spec =
      {
        data: String,
        labels: top,
        name: String,
        templating: DockerEngineRuby::ConfigSpec::Templating
      }

    class ConfigSpec < DockerEngineRuby::Internal::Type::BaseModel
      attr_reader data: String?

      def data=: (String) -> String

      attr_reader labels: top?

      def labels=: (top) -> top

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader templating: DockerEngineRuby::ConfigSpec::Templating?

      def templating=: (
        DockerEngineRuby::ConfigSpec::Templating
      ) -> DockerEngineRuby::ConfigSpec::Templating

      def initialize: (
        ?data: String,
        ?labels: top,
        ?name: String,
        ?templating: DockerEngineRuby::ConfigSpec::Templating
      ) -> void

      def to_hash: -> {
        data: String,
        labels: top,
        name: String,
        templating: DockerEngineRuby::ConfigSpec::Templating
      }

      type templating = { name: String, options: top }

      class Templating < DockerEngineRuby::Internal::Type::BaseModel
        attr_accessor name: String

        attr_reader options: top?

        def options=: (top) -> top

        def initialize: (name: String, ?options: top) -> void

        def to_hash: -> { name: String, options: top }
      end
    end
  end
end
