module DockerEngineRuby
  module Models
    type config_update_params =
      { spec: DockerEngineRuby::ConfigSpec, id: String, version: Integer }
      & DockerEngineRuby::Internal::Type::request_parameters

    class ConfigUpdateParams < DockerEngineRuby::Internal::Type::BaseModel
      extend DockerEngineRuby::Internal::Type::RequestParameters::Converter
      include DockerEngineRuby::Internal::Type::RequestParameters

      attr_accessor spec: DockerEngineRuby::ConfigSpec

      attr_accessor id: String

      attr_accessor version: Integer

      def initialize: (
        spec: DockerEngineRuby::ConfigSpec,
        id: String,
        version: Integer,
        ?request_options: DockerEngineRuby::request_opts
      ) -> void

      def to_hash: -> {
        spec: DockerEngineRuby::ConfigSpec,
        id: String,
        version: Integer,
        request_options: DockerEngineRuby::RequestOptions
      }
    end
  end
end
