module DockerEngineRuby
  module Models
    type connect_request =
      {
        container: String,
        endpoint_config: DockerEngineRuby::ConnectRequest::EndpointConfig?
      }

    class ConnectRequest < DockerEngineRuby::Internal::Type::BaseModel
      attr_accessor container: String

      attr_accessor endpoint_config: DockerEngineRuby::ConnectRequest::EndpointConfig?

      def initialize: (
        container: String,
        ?endpoint_config: DockerEngineRuby::ConnectRequest::EndpointConfig?
      ) -> void

      def to_hash: -> {
        container: String,
        endpoint_config: DockerEngineRuby::ConnectRequest::EndpointConfig?
      }

      type endpoint_config =
        {
          aliases: ::Array[String],
          dns_names: ::Array[String],
          driver_opts: top?,
          endpoint_id: String,
          gateway: String,
          :global_i_pv6_address => String,
          :global_i_pv6_prefix_len => Integer,
          gw_priority: Integer,
          ip_address: String,
          ipam_config: DockerEngineRuby::ConnectRequest::EndpointConfig::IpamConfig,
          ip_prefix_len: Integer,
          :i_pv6_gateway => String,
          links: ::Array[String],
          mac_address: String,
          network_id: String
        }

      class EndpointConfig < DockerEngineRuby::Internal::Type::BaseModel
        attr_reader aliases: ::Array[String]?

        def aliases=: (::Array[String]) -> ::Array[String]

        attr_reader dns_names: ::Array[String]?

        def dns_names=: (::Array[String]) -> ::Array[String]

        attr_accessor driver_opts: top?

        attr_reader endpoint_id: String?

        def endpoint_id=: (String) -> String

        attr_reader gateway: String?

        def gateway=: (String) -> String

        attr_reader global_i_pv6_address: String?

        def global_i_pv6_address=: (String) -> String

        attr_reader global_i_pv6_prefix_len: Integer?

        def global_i_pv6_prefix_len=: (Integer) -> Integer

        attr_reader gw_priority: Integer?

        def gw_priority=: (Integer) -> Integer

        attr_reader ip_address: String?

        def ip_address=: (String) -> String

        attr_reader ipam_config: DockerEngineRuby::ConnectRequest::EndpointConfig::IpamConfig?

        def ipam_config=: (
          DockerEngineRuby::ConnectRequest::EndpointConfig::IpamConfig
        ) -> DockerEngineRuby::ConnectRequest::EndpointConfig::IpamConfig

        attr_reader ip_prefix_len: Integer?

        def ip_prefix_len=: (Integer) -> Integer

        attr_reader i_pv6_gateway: String?

        def i_pv6_gateway=: (String) -> String

        attr_reader links: ::Array[String]?

        def links=: (::Array[String]) -> ::Array[String]

        attr_reader mac_address: String?

        def mac_address=: (String) -> String

        attr_reader network_id: String?

        def network_id=: (String) -> String

        def initialize: (
          ?aliases: ::Array[String],
          ?dns_names: ::Array[String],
          ?driver_opts: top?,
          ?endpoint_id: String,
          ?gateway: String,
          ?global_i_pv6_address: String,
          ?global_i_pv6_prefix_len: Integer,
          ?gw_priority: Integer,
          ?ip_address: String,
          ?ipam_config: DockerEngineRuby::ConnectRequest::EndpointConfig::IpamConfig,
          ?ip_prefix_len: Integer,
          ?i_pv6_gateway: String,
          ?links: ::Array[String],
          ?mac_address: String,
          ?network_id: String
        ) -> void

        def to_hash: -> {
          aliases: ::Array[String],
          dns_names: ::Array[String],
          driver_opts: top?,
          endpoint_id: String,
          gateway: String,
          :global_i_pv6_address => String,
          :global_i_pv6_prefix_len => Integer,
          gw_priority: Integer,
          ip_address: String,
          ipam_config: DockerEngineRuby::ConnectRequest::EndpointConfig::IpamConfig,
          ip_prefix_len: Integer,
          :i_pv6_gateway => String,
          links: ::Array[String],
          mac_address: String,
          network_id: String
        }

        type ipam_config =
          {
            :i_pv4_address => String,
            :i_pv6_address => String,
            link_local_ips: ::Array[String]
          }

        class IpamConfig < DockerEngineRuby::Internal::Type::BaseModel
          attr_reader i_pv4_address: String?

          def i_pv4_address=: (String) -> String

          attr_reader i_pv6_address: String?

          def i_pv6_address=: (String) -> String

          attr_reader link_local_ips: ::Array[String]?

          def link_local_ips=: (::Array[String]) -> ::Array[String]

          def initialize: (
            ?i_pv4_address: String,
            ?i_pv6_address: String,
            ?link_local_ips: ::Array[String]
          ) -> void

          def to_hash: -> {
            :i_pv4_address => String,
            :i_pv6_address => String,
            link_local_ips: ::Array[String]
          }
        end
      end
    end
  end
end
