module DockerEngineRuby
  module Models
    type container_inspect_params =
      { id: String, size: bool }
      & DockerEngineRuby::Internal::Type::request_parameters

    class ContainerInspectParams < DockerEngineRuby::Internal::Type::BaseModel
      extend DockerEngineRuby::Internal::Type::RequestParameters::Converter
      include DockerEngineRuby::Internal::Type::RequestParameters

      attr_accessor id: String

      attr_reader size: bool?

      def size=: (bool) -> bool

      def initialize: (
        id: String,
        ?size: bool,
        ?request_options: DockerEngineRuby::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        size: bool,
        request_options: DockerEngineRuby::RequestOptions
      }
    end
  end
end
