module DockerEngineRuby
  module Models
    type container_create_params =
      { name: String, platform: String }
      & DockerEngineRuby::Internal::Type::request_parameters

    class ContainerCreateParams < DockerEngineRuby::Internal::Type::BaseModel
      extend DockerEngineRuby::Internal::Type::RequestParameters::Converter
      include DockerEngineRuby::Internal::Type::RequestParameters

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader platform: String?

      def platform=: (String) -> String

      def initialize: (
        ?name: String,
        ?platform: String,
        ?request_options: DockerEngineRuby::request_opts
      ) -> void

      def to_hash: -> {
        name: String,
        platform: String,
        request_options: DockerEngineRuby::RequestOptions
      }
    end
  end
end
