module DockerEngineRuby
  module Models
    type container_attach_params =
      {
        detach_keys: String,
        logs: bool,
        stderr: bool,
        stdin: bool,
        stdout: bool,
        stream: bool
      }
      & DockerEngineRuby::Internal::Type::request_parameters

    class ContainerAttachParams < DockerEngineRuby::Internal::Type::BaseModel
      extend DockerEngineRuby::Internal::Type::RequestParameters::Converter
      include DockerEngineRuby::Internal::Type::RequestParameters

      attr_reader detach_keys: String?

      def detach_keys=: (String) -> String

      attr_reader logs: bool?

      def logs=: (bool) -> bool

      attr_reader stderr: bool?

      def stderr=: (bool) -> bool

      attr_reader stdin: bool?

      def stdin=: (bool) -> bool

      attr_reader stdout: bool?

      def stdout=: (bool) -> bool

      attr_reader stream: bool?

      def stream=: (bool) -> bool

      def initialize: (
        ?detach_keys: String,
        ?logs: bool,
        ?stderr: bool,
        ?stdin: bool,
        ?stdout: bool,
        ?stream: bool,
        ?request_options: DockerEngineRuby::request_opts
      ) -> void

      def to_hash: -> {
        detach_keys: String,
        logs: bool,
        stderr: bool,
        stdin: bool,
        stdout: bool,
        stream: bool,
        request_options: DockerEngineRuby::RequestOptions
      }
    end
  end
end
