module DockerEngineRuby
  module Models
    type create_request =
      {
        cluster_volume_spec: DockerEngineRuby::CreateRequest::ClusterVolumeSpec,
        driver: String,
        driver_opts: ::Hash[Symbol, String],
        labels: ::Hash[Symbol, String],
        name: String
      }

    class CreateRequest < DockerEngineRuby::Internal::Type::BaseModel
      attr_reader cluster_volume_spec: DockerEngineRuby::CreateRequest::ClusterVolumeSpec?

      def cluster_volume_spec=: (
        DockerEngineRuby::CreateRequest::ClusterVolumeSpec
      ) -> DockerEngineRuby::CreateRequest::ClusterVolumeSpec

      attr_reader driver: String?

      def driver=: (String) -> String

      attr_reader driver_opts: ::Hash[Symbol, String]?

      def driver_opts=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_reader labels: ::Hash[Symbol, String]?

      def labels=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_reader name: String?

      def name=: (String) -> String

      def initialize: (
        ?cluster_volume_spec: DockerEngineRuby::CreateRequest::ClusterVolumeSpec,
        ?driver: String,
        ?driver_opts: ::Hash[Symbol, String],
        ?labels: ::Hash[Symbol, String],
        ?name: String
      ) -> void

      def to_hash: -> {
        cluster_volume_spec: DockerEngineRuby::CreateRequest::ClusterVolumeSpec,
        driver: String,
        driver_opts: ::Hash[Symbol, String],
        labels: ::Hash[Symbol, String],
        name: String
      }

      type cluster_volume_spec =
        {
          access_mode: DockerEngineRuby::CreateRequest::ClusterVolumeSpec::AccessMode,
          group: String
        }

      class ClusterVolumeSpec < DockerEngineRuby::Internal::Type::BaseModel
        attr_reader access_mode: DockerEngineRuby::CreateRequest::ClusterVolumeSpec::AccessMode?

        def access_mode=: (
          DockerEngineRuby::CreateRequest::ClusterVolumeSpec::AccessMode
        ) -> DockerEngineRuby::CreateRequest::ClusterVolumeSpec::AccessMode

        attr_reader group: String?

        def group=: (String) -> String

        def initialize: (
          ?access_mode: DockerEngineRuby::CreateRequest::ClusterVolumeSpec::AccessMode,
          ?group: String
        ) -> void

        def to_hash: -> {
          access_mode: DockerEngineRuby::CreateRequest::ClusterVolumeSpec::AccessMode,
          group: String
        }

        type access_mode =
          {
            accessibility_requirements: DockerEngineRuby::CreateRequest::ClusterVolumeSpec::AccessMode::AccessibilityRequirements,
            availability: DockerEngineRuby::Models::CreateRequest::ClusterVolumeSpec::AccessMode::availability,
            capacity_range: DockerEngineRuby::CreateRequest::ClusterVolumeSpec::AccessMode::CapacityRange,
            mount_volume: ::Hash[Symbol, top],
            scope: DockerEngineRuby::Models::CreateRequest::ClusterVolumeSpec::AccessMode::scope,
            secrets: ::Array[DockerEngineRuby::CreateRequest::ClusterVolumeSpec::AccessMode::Secret],
            sharing: DockerEngineRuby::Models::CreateRequest::ClusterVolumeSpec::AccessMode::sharing
          }

        class AccessMode < DockerEngineRuby::Internal::Type::BaseModel
          attr_reader accessibility_requirements: DockerEngineRuby::CreateRequest::ClusterVolumeSpec::AccessMode::AccessibilityRequirements?

          def accessibility_requirements=: (
            DockerEngineRuby::CreateRequest::ClusterVolumeSpec::AccessMode::AccessibilityRequirements
          ) -> DockerEngineRuby::CreateRequest::ClusterVolumeSpec::AccessMode::AccessibilityRequirements

          attr_reader availability: DockerEngineRuby::Models::CreateRequest::ClusterVolumeSpec::AccessMode::availability?

          def availability=: (
            DockerEngineRuby::Models::CreateRequest::ClusterVolumeSpec::AccessMode::availability
          ) -> DockerEngineRuby::Models::CreateRequest::ClusterVolumeSpec::AccessMode::availability

          attr_reader capacity_range: DockerEngineRuby::CreateRequest::ClusterVolumeSpec::AccessMode::CapacityRange?

          def capacity_range=: (
            DockerEngineRuby::CreateRequest::ClusterVolumeSpec::AccessMode::CapacityRange
          ) -> DockerEngineRuby::CreateRequest::ClusterVolumeSpec::AccessMode::CapacityRange

          attr_reader mount_volume: ::Hash[Symbol, top]?

          def mount_volume=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

          attr_reader scope: DockerEngineRuby::Models::CreateRequest::ClusterVolumeSpec::AccessMode::scope?

          def scope=: (
            DockerEngineRuby::Models::CreateRequest::ClusterVolumeSpec::AccessMode::scope
          ) -> DockerEngineRuby::Models::CreateRequest::ClusterVolumeSpec::AccessMode::scope

          attr_reader secrets: ::Array[DockerEngineRuby::CreateRequest::ClusterVolumeSpec::AccessMode::Secret]?

          def secrets=: (
            ::Array[DockerEngineRuby::CreateRequest::ClusterVolumeSpec::AccessMode::Secret]
          ) -> ::Array[DockerEngineRuby::CreateRequest::ClusterVolumeSpec::AccessMode::Secret]

          attr_reader sharing: DockerEngineRuby::Models::CreateRequest::ClusterVolumeSpec::AccessMode::sharing?

          def sharing=: (
            DockerEngineRuby::Models::CreateRequest::ClusterVolumeSpec::AccessMode::sharing
          ) -> DockerEngineRuby::Models::CreateRequest::ClusterVolumeSpec::AccessMode::sharing

          def initialize: (
            ?accessibility_requirements: DockerEngineRuby::CreateRequest::ClusterVolumeSpec::AccessMode::AccessibilityRequirements,
            ?availability: DockerEngineRuby::Models::CreateRequest::ClusterVolumeSpec::AccessMode::availability,
            ?capacity_range: DockerEngineRuby::CreateRequest::ClusterVolumeSpec::AccessMode::CapacityRange,
            ?mount_volume: ::Hash[Symbol, top],
            ?scope: DockerEngineRuby::Models::CreateRequest::ClusterVolumeSpec::AccessMode::scope,
            ?secrets: ::Array[DockerEngineRuby::CreateRequest::ClusterVolumeSpec::AccessMode::Secret],
            ?sharing: DockerEngineRuby::Models::CreateRequest::ClusterVolumeSpec::AccessMode::sharing
          ) -> void

          def to_hash: -> {
            accessibility_requirements: DockerEngineRuby::CreateRequest::ClusterVolumeSpec::AccessMode::AccessibilityRequirements,
            availability: DockerEngineRuby::Models::CreateRequest::ClusterVolumeSpec::AccessMode::availability,
            capacity_range: DockerEngineRuby::CreateRequest::ClusterVolumeSpec::AccessMode::CapacityRange,
            mount_volume: ::Hash[Symbol, top],
            scope: DockerEngineRuby::Models::CreateRequest::ClusterVolumeSpec::AccessMode::scope,
            secrets: ::Array[DockerEngineRuby::CreateRequest::ClusterVolumeSpec::AccessMode::Secret],
            sharing: DockerEngineRuby::Models::CreateRequest::ClusterVolumeSpec::AccessMode::sharing
          }

          type accessibility_requirements =
            {
              preferred: ::Array[::Hash[Symbol, String]],
              requisite: ::Array[::Hash[Symbol, String]]
            }

          class AccessibilityRequirements < DockerEngineRuby::Internal::Type::BaseModel
            attr_reader preferred: ::Array[::Hash[Symbol, String]]?

            def preferred=: (
              ::Array[::Hash[Symbol, String]]
            ) -> ::Array[::Hash[Symbol, String]]

            attr_reader requisite: ::Array[::Hash[Symbol, String]]?

            def requisite=: (
              ::Array[::Hash[Symbol, String]]
            ) -> ::Array[::Hash[Symbol, String]]

            def initialize: (
              ?preferred: ::Array[::Hash[Symbol, String]],
              ?requisite: ::Array[::Hash[Symbol, String]]
            ) -> void

            def to_hash: -> {
              preferred: ::Array[::Hash[Symbol, String]],
              requisite: ::Array[::Hash[Symbol, String]]
            }
          end

          type availability = :active | :pause | :drain

          module Availability
            extend DockerEngineRuby::Internal::Type::Enum

            ACTIVE: :active
            PAUSE: :pause
            DRAIN: :drain

            def self?.values: -> ::Array[DockerEngineRuby::Models::CreateRequest::ClusterVolumeSpec::AccessMode::availability]
          end

          type capacity_range =
            { limit_bytes: Integer, required_bytes: Integer }

          class CapacityRange < DockerEngineRuby::Internal::Type::BaseModel
            attr_reader limit_bytes: Integer?

            def limit_bytes=: (Integer) -> Integer

            attr_reader required_bytes: Integer?

            def required_bytes=: (Integer) -> Integer

            def initialize: (
              ?limit_bytes: Integer,
              ?required_bytes: Integer
            ) -> void

            def to_hash: -> { limit_bytes: Integer, required_bytes: Integer }
          end

          type scope = :single | :multi

          module Scope
            extend DockerEngineRuby::Internal::Type::Enum

            SINGLE: :single
            MULTI: :multi

            def self?.values: -> ::Array[DockerEngineRuby::Models::CreateRequest::ClusterVolumeSpec::AccessMode::scope]
          end

          type secret = { key: String, secret: String }

          class Secret < DockerEngineRuby::Internal::Type::BaseModel
            attr_reader key: String?

            def key=: (String) -> String

            attr_reader secret: String?

            def secret=: (String) -> String

            def initialize: (?key: String, ?secret: String) -> void

            def to_hash: -> { key: String, secret: String }
          end

          type sharing = :none | :readonly | :onewriter | :all

          module Sharing
            extend DockerEngineRuby::Internal::Type::Enum

            NONE: :none
            READONLY: :readonly
            ONEWRITER: :onewriter
            ALL: :all

            def self?.values: -> ::Array[DockerEngineRuby::Models::CreateRequest::ClusterVolumeSpec::AccessMode::sharing]
          end
        end
      end
    end
  end
end
