module DockerEngineRuby
  module Models
    type disconnect_request = { container: String, force: bool }

    class DisconnectRequest < DockerEngineRuby::Internal::Type::BaseModel
      attr_accessor container: String

      attr_reader force: bool?

      def force=: (bool) -> bool

      def initialize: (container: String, ?force: bool) -> void

      def to_hash: -> { container: String, force: bool }
    end
  end
end
