module DockerEngineRuby
  module Models
    type image_list_params =
      {
        all: bool,
        digests: bool,
        filters: String,
        manifests: bool,
        shared_size: bool
      }
      & DockerEngineRuby::Internal::Type::request_parameters

    class ImageListParams < DockerEngineRuby::Internal::Type::BaseModel
      extend DockerEngineRuby::Internal::Type::RequestParameters::Converter
      include DockerEngineRuby::Internal::Type::RequestParameters

      attr_reader all: bool?

      def all=: (bool) -> bool

      attr_reader digests: bool?

      def digests=: (bool) -> bool

      attr_reader filters: String?

      def filters=: (String) -> String

      attr_reader manifests: bool?

      def manifests=: (bool) -> bool

      attr_reader shared_size: bool?

      def shared_size=: (bool) -> bool

      def initialize: (
        ?all: bool,
        ?digests: bool,
        ?filters: String,
        ?manifests: bool,
        ?shared_size: bool,
        ?request_options: DockerEngineRuby::request_opts
      ) -> void

      def to_hash: -> {
        all: bool,
        digests: bool,
        filters: String,
        manifests: bool,
        shared_size: bool,
        request_options: DockerEngineRuby::RequestOptions
      }
    end
  end
end
