module DockerEngineRuby
  module Models
    type image_search_response_item =
      {
        description: String,
        is_automated: bool,
        is_official: bool,
        name: String,
        star_count: Integer
      }

    class ImageSearchResponseItem < DockerEngineRuby::Internal::Type::BaseModel
      attr_reader description: String?

      def description=: (String) -> String

      attr_reader is_automated: bool?

      def is_automated=: (bool) -> bool

      attr_reader is_official: bool?

      def is_official=: (bool) -> bool

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader star_count: Integer?

      def star_count=: (Integer) -> Integer

      def initialize: (
        ?description: String,
        ?is_automated: bool,
        ?is_official: bool,
        ?name: String,
        ?star_count: Integer
      ) -> void

      def to_hash: -> {
        description: String,
        is_automated: bool,
        is_official: bool,
        name: String,
        star_count: Integer
      }
    end

    type image_search_response =
      ::Array[DockerEngineRuby::Models::ImageSearchResponseItem]

    ImageSearchResponse: DockerEngineRuby::Internal::Type::Converter
  end
end
