module DockerEngineRuby
  module Models
    type image_build_prune_params =
      {
        all: bool,
        filters: String,
        max_used_space: Integer,
        min_free_space: Integer,
        reserved_space: Integer
      }
      & DockerEngineRuby::Internal::Type::request_parameters

    class ImageBuildPruneParams < DockerEngineRuby::Internal::Type::BaseModel
      extend DockerEngineRuby::Internal::Type::RequestParameters::Converter
      include DockerEngineRuby::Internal::Type::RequestParameters

      attr_reader all: bool?

      def all=: (bool) -> bool

      attr_reader filters: String?

      def filters=: (String) -> String

      attr_reader max_used_space: Integer?

      def max_used_space=: (Integer) -> Integer

      attr_reader min_free_space: Integer?

      def min_free_space=: (Integer) -> Integer

      attr_reader reserved_space: Integer?

      def reserved_space=: (Integer) -> Integer

      def initialize: (
        ?all: bool,
        ?filters: String,
        ?max_used_space: Integer,
        ?min_free_space: Integer,
        ?reserved_space: Integer,
        ?request_options: DockerEngineRuby::request_opts
      ) -> void

      def to_hash: -> {
        all: bool,
        filters: String,
        max_used_space: Integer,
        min_free_space: Integer,
        reserved_space: Integer,
        request_options: DockerEngineRuby::RequestOptions
      }
    end
  end
end
