module DockerEngineRuby
  module Models
    type image_tag_params =
      { repo: String, tag: String }
      & DockerEngineRuby::Internal::Type::request_parameters

    class ImageTagParams < DockerEngineRuby::Internal::Type::BaseModel
      extend DockerEngineRuby::Internal::Type::RequestParameters::Converter
      include DockerEngineRuby::Internal::Type::RequestParameters

      attr_reader repo: String?

      def repo=: (String) -> String

      attr_reader tag: String?

      def tag=: (String) -> String

      def initialize: (
        ?repo: String,
        ?tag: String,
        ?request_options: DockerEngineRuby::request_opts
      ) -> void

      def to_hash: -> {
        repo: String,
        tag: String,
        request_options: DockerEngineRuby::RequestOptions
      }
    end
  end
end
