module DockerEngineRuby
  module Models
    type image_search_params =
      { term: String, filters: String, limit: Integer }
      & DockerEngineRuby::Internal::Type::request_parameters

    class ImageSearchParams < DockerEngineRuby::Internal::Type::BaseModel
      extend DockerEngineRuby::Internal::Type::RequestParameters::Converter
      include DockerEngineRuby::Internal::Type::RequestParameters

      attr_accessor term: String

      attr_reader filters: String?

      def filters=: (String) -> String

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      def initialize: (
        term: String,
        ?filters: String,
        ?limit: Integer,
        ?request_options: DockerEngineRuby::request_opts
      ) -> void

      def to_hash: -> {
        term: String,
        filters: String,
        limit: Integer,
        request_options: DockerEngineRuby::RequestOptions
      }
    end
  end
end
