module DockerEngineRuby
  module Models
    type image_get_params =
      { name: String, platform: ::Array[String] }
      & DockerEngineRuby::Internal::Type::request_parameters

    class ImageGetParams < DockerEngineRuby::Internal::Type::BaseModel
      extend DockerEngineRuby::Internal::Type::RequestParameters::Converter
      include DockerEngineRuby::Internal::Type::RequestParameters

      attr_accessor name: String

      attr_reader platform: ::Array[String]?

      def platform=: (::Array[String]) -> ::Array[String]

      def initialize: (
        name: String,
        ?platform: ::Array[String],
        ?request_options: DockerEngineRuby::request_opts
      ) -> void

      def to_hash: -> {
        name: String,
        platform: ::Array[String],
        request_options: DockerEngineRuby::RequestOptions
      }
    end
  end
end
