module DockerEngineRuby
  module Models
    type inspect_response =
      {
        arguments: ::Array[String],
        entrypoint: String,
        privileged: bool,
        tty: bool,
        user: String
      }

    class InspectResponse < DockerEngineRuby::Internal::Type::BaseModel
      attr_reader arguments: ::Array[String]?

      def arguments=: (::Array[String]) -> ::Array[String]

      attr_reader entrypoint: String?

      def entrypoint=: (String) -> String

      attr_reader privileged: bool?

      def privileged=: (bool) -> bool

      attr_reader tty: bool?

      def tty=: (bool) -> bool

      attr_reader user: String?

      def user=: (String) -> String

      def initialize: (
        ?arguments: ::Array[String],
        ?entrypoint: String,
        ?privileged: bool,
        ?tty: bool,
        ?user: String
      ) -> void

      def to_hash: -> {
        arguments: ::Array[String],
        entrypoint: String,
        privileged: bool,
        tty: bool,
        user: String
      }
    end
  end
end
