module DockerEngineRuby
  module Models
    type inspect_ =
      {
        descriptor: DockerEngineRuby::Inspect::Descriptor,
        platforms: ::Array[DockerEngineRuby::Inspect::Platform]
      }

    class Inspect < DockerEngineRuby::Internal::Type::BaseModel
      attr_accessor descriptor: DockerEngineRuby::Inspect::Descriptor

      attr_accessor platforms: ::Array[DockerEngineRuby::Inspect::Platform]

      def initialize: (
        descriptor: DockerEngineRuby::Inspect::Descriptor,
        platforms: ::Array[DockerEngineRuby::Inspect::Platform]
      ) -> void

      def to_hash: -> {
        descriptor: DockerEngineRuby::Inspect::Descriptor,
        platforms: ::Array[DockerEngineRuby::Inspect::Platform]
      }

      type descriptor =
        {
          annotations: ::Hash[Symbol, String]?,
          artifact_type: String?,
          data: String?,
          digest: String,
          media_type: String,
          platform: DockerEngineRuby::Inspect::Descriptor::Platform,
          size: Integer,
          urls: ::Array[String]?
        }

      class Descriptor < DockerEngineRuby::Internal::Type::BaseModel
        attr_accessor annotations: ::Hash[Symbol, String]?

        attr_accessor artifact_type: String?

        attr_accessor data: String?

        attr_reader digest: String?

        def digest=: (String) -> String

        attr_reader media_type: String?

        def media_type=: (String) -> String

        attr_reader platform: DockerEngineRuby::Inspect::Descriptor::Platform?

        def platform=: (
          DockerEngineRuby::Inspect::Descriptor::Platform
        ) -> DockerEngineRuby::Inspect::Descriptor::Platform

        attr_reader size: Integer?

        def size=: (Integer) -> Integer

        attr_accessor urls: ::Array[String]?

        def initialize: (
          ?annotations: ::Hash[Symbol, String]?,
          ?artifact_type: String?,
          ?data: String?,
          ?digest: String,
          ?media_type: String,
          ?platform: DockerEngineRuby::Inspect::Descriptor::Platform,
          ?size: Integer,
          ?urls: ::Array[String]?
        ) -> void

        def to_hash: -> {
          annotations: ::Hash[Symbol, String]?,
          artifact_type: String?,
          data: String?,
          digest: String,
          media_type: String,
          platform: DockerEngineRuby::Inspect::Descriptor::Platform,
          size: Integer,
          urls: ::Array[String]?
        }

        type platform =
          {
            architecture: String,
            os: String,
            os_features: ::Array[String],
            os_version: String,
            variant: String
          }

        class Platform < DockerEngineRuby::Internal::Type::BaseModel
          attr_reader architecture: String?

          def architecture=: (String) -> String

          attr_reader os: String?

          def os=: (String) -> String

          attr_reader os_features: ::Array[String]?

          def os_features=: (::Array[String]) -> ::Array[String]

          attr_reader os_version: String?

          def os_version=: (String) -> String

          attr_reader variant: String?

          def variant=: (String) -> String

          def initialize: (
            ?architecture: String,
            ?os: String,
            ?os_features: ::Array[String],
            ?os_version: String,
            ?variant: String
          ) -> void

          def to_hash: -> {
            architecture: String,
            os: String,
            os_features: ::Array[String],
            os_version: String,
            variant: String
          }
        end
      end

      type platform =
        {
          architecture: String,
          os: String,
          os_features: ::Array[String],
          os_version: String,
          variant: String
        }

      class Platform < DockerEngineRuby::Internal::Type::BaseModel
        attr_reader architecture: String?

        def architecture=: (String) -> String

        attr_reader os: String?

        def os=: (String) -> String

        attr_reader os_features: ::Array[String]?

        def os_features=: (::Array[String]) -> ::Array[String]

        attr_reader os_version: String?

        def os_version=: (String) -> String

        attr_reader variant: String?

        def variant=: (String) -> String

        def initialize: (
          ?architecture: String,
          ?os: String,
          ?os_features: ::Array[String],
          ?os_version: String,
          ?variant: String
        ) -> void

        def to_hash: -> {
          architecture: String,
          os: String,
          os_features: ::Array[String],
          os_version: String,
          variant: String
        }
      end
    end
  end
end
