module DockerEngineRuby
  module Models
    type network_create_response = { id: String, warning: String }

    class NetworkCreateResponse < DockerEngineRuby::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor warning: String

      def initialize: (id: String, warning: String) -> void

      def to_hash: -> { id: String, warning: String }
    end
  end
end
