module DockerEngineRuby
  module Models
    type node =
      {
        created_at: Time,
        description: DockerEngineRuby::Node::Description,
        id: String,
        manager_status: DockerEngineRuby::Node::ManagerStatus,
        spec: DockerEngineRuby::NodeSpec,
        status: DockerEngineRuby::Node::Status,
        updated_at: Time,
        version: DockerEngineRuby::Node::Version
      }

    class Node < DockerEngineRuby::Internal::Type::BaseModel
      attr_reader created_at: Time?

      def created_at=: (Time) -> Time

      attr_reader description: DockerEngineRuby::Node::Description?

      def description=: (
        DockerEngineRuby::Node::Description
      ) -> DockerEngineRuby::Node::Description

      attr_reader id: String?

      def id=: (String) -> String

      attr_reader manager_status: DockerEngineRuby::Node::ManagerStatus?

      def manager_status=: (
        DockerEngineRuby::Node::ManagerStatus
      ) -> DockerEngineRuby::Node::ManagerStatus

      attr_reader spec: DockerEngineRuby::NodeSpec?

      def spec=: (DockerEngineRuby::NodeSpec) -> DockerEngineRuby::NodeSpec

      attr_reader status: DockerEngineRuby::Node::Status?

      def status=: (
        DockerEngineRuby::Node::Status
      ) -> DockerEngineRuby::Node::Status

      attr_reader updated_at: Time?

      def updated_at=: (Time) -> Time

      attr_reader version: DockerEngineRuby::Node::Version?

      def version=: (
        DockerEngineRuby::Node::Version
      ) -> DockerEngineRuby::Node::Version

      def initialize: (
        ?created_at: Time,
        ?description: DockerEngineRuby::Node::Description,
        ?id: String,
        ?manager_status: DockerEngineRuby::Node::ManagerStatus,
        ?spec: DockerEngineRuby::NodeSpec,
        ?status: DockerEngineRuby::Node::Status,
        ?updated_at: Time,
        ?version: DockerEngineRuby::Node::Version
      ) -> void

      def to_hash: -> {
        created_at: Time,
        description: DockerEngineRuby::Node::Description,
        id: String,
        manager_status: DockerEngineRuby::Node::ManagerStatus,
        spec: DockerEngineRuby::NodeSpec,
        status: DockerEngineRuby::Node::Status,
        updated_at: Time,
        version: DockerEngineRuby::Node::Version
      }

      type description =
        {
          engine: DockerEngineRuby::Node::Description::Engine,
          hostname: String,
          platform: DockerEngineRuby::Node::Description::Platform,
          resources: DockerEngineRuby::Node::Description::Resources,
          tls_info: DockerEngineRuby::Node::Description::TlsInfo
        }

      class Description < DockerEngineRuby::Internal::Type::BaseModel
        attr_reader engine: DockerEngineRuby::Node::Description::Engine?

        def engine=: (
          DockerEngineRuby::Node::Description::Engine
        ) -> DockerEngineRuby::Node::Description::Engine

        attr_reader hostname: String?

        def hostname=: (String) -> String

        attr_reader platform: DockerEngineRuby::Node::Description::Platform?

        def platform=: (
          DockerEngineRuby::Node::Description::Platform
        ) -> DockerEngineRuby::Node::Description::Platform

        attr_reader resources: DockerEngineRuby::Node::Description::Resources?

        def resources=: (
          DockerEngineRuby::Node::Description::Resources
        ) -> DockerEngineRuby::Node::Description::Resources

        attr_reader tls_info: DockerEngineRuby::Node::Description::TlsInfo?

        def tls_info=: (
          DockerEngineRuby::Node::Description::TlsInfo
        ) -> DockerEngineRuby::Node::Description::TlsInfo

        def initialize: (
          ?engine: DockerEngineRuby::Node::Description::Engine,
          ?hostname: String,
          ?platform: DockerEngineRuby::Node::Description::Platform,
          ?resources: DockerEngineRuby::Node::Description::Resources,
          ?tls_info: DockerEngineRuby::Node::Description::TlsInfo
        ) -> void

        def to_hash: -> {
          engine: DockerEngineRuby::Node::Description::Engine,
          hostname: String,
          platform: DockerEngineRuby::Node::Description::Platform,
          resources: DockerEngineRuby::Node::Description::Resources,
          tls_info: DockerEngineRuby::Node::Description::TlsInfo
        }

        type engine =
          {
            engine_version: String,
            labels: ::Hash[Symbol, String],
            plugins: ::Array[DockerEngineRuby::Node::Description::Engine::Plugin]
          }

        class Engine < DockerEngineRuby::Internal::Type::BaseModel
          attr_reader engine_version: String?

          def engine_version=: (String) -> String

          attr_reader labels: ::Hash[Symbol, String]?

          def labels=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

          attr_reader plugins: ::Array[DockerEngineRuby::Node::Description::Engine::Plugin]?

          def plugins=: (
            ::Array[DockerEngineRuby::Node::Description::Engine::Plugin]
          ) -> ::Array[DockerEngineRuby::Node::Description::Engine::Plugin]

          def initialize: (
            ?engine_version: String,
            ?labels: ::Hash[Symbol, String],
            ?plugins: ::Array[DockerEngineRuby::Node::Description::Engine::Plugin]
          ) -> void

          def to_hash: -> {
            engine_version: String,
            labels: ::Hash[Symbol, String],
            plugins: ::Array[DockerEngineRuby::Node::Description::Engine::Plugin]
          }

          type plugin = { name: String, type: String }

          class Plugin < DockerEngineRuby::Internal::Type::BaseModel
            attr_reader name: String?

            def name=: (String) -> String

            attr_reader type: String?

            def type=: (String) -> String

            def initialize: (?name: String, ?type: String) -> void

            def to_hash: -> { name: String, type: String }
          end
        end

        type platform = { architecture: String, os: String }

        class Platform < DockerEngineRuby::Internal::Type::BaseModel
          attr_reader architecture: String?

          def architecture=: (String) -> String

          attr_reader os: String?

          def os=: (String) -> String

          def initialize: (?architecture: String, ?os: String) -> void

          def to_hash: -> { architecture: String, os: String }
        end

        type resources =
          {
            generic_resources: ::Array[DockerEngineRuby::Node::Description::Resources::GenericResource],
            memory_bytes: Integer,
            nano_cpus: Integer
          }

        class Resources < DockerEngineRuby::Internal::Type::BaseModel
          attr_reader generic_resources: ::Array[DockerEngineRuby::Node::Description::Resources::GenericResource]?

          def generic_resources=: (
            ::Array[DockerEngineRuby::Node::Description::Resources::GenericResource]
          ) -> ::Array[DockerEngineRuby::Node::Description::Resources::GenericResource]

          attr_reader memory_bytes: Integer?

          def memory_bytes=: (Integer) -> Integer

          attr_reader nano_cpus: Integer?

          def nano_cpus=: (Integer) -> Integer

          def initialize: (
            ?generic_resources: ::Array[DockerEngineRuby::Node::Description::Resources::GenericResource],
            ?memory_bytes: Integer,
            ?nano_cpus: Integer
          ) -> void

          def to_hash: -> {
            generic_resources: ::Array[DockerEngineRuby::Node::Description::Resources::GenericResource],
            memory_bytes: Integer,
            nano_cpus: Integer
          }

          type generic_resource =
            {
              discrete_resource_spec: DockerEngineRuby::Node::Description::Resources::GenericResource::DiscreteResourceSpec,
              named_resource_spec: DockerEngineRuby::Node::Description::Resources::GenericResource::NamedResourceSpec
            }

          class GenericResource < DockerEngineRuby::Internal::Type::BaseModel
            attr_reader discrete_resource_spec: DockerEngineRuby::Node::Description::Resources::GenericResource::DiscreteResourceSpec?

            def discrete_resource_spec=: (
              DockerEngineRuby::Node::Description::Resources::GenericResource::DiscreteResourceSpec
            ) -> DockerEngineRuby::Node::Description::Resources::GenericResource::DiscreteResourceSpec

            attr_reader named_resource_spec: DockerEngineRuby::Node::Description::Resources::GenericResource::NamedResourceSpec?

            def named_resource_spec=: (
              DockerEngineRuby::Node::Description::Resources::GenericResource::NamedResourceSpec
            ) -> DockerEngineRuby::Node::Description::Resources::GenericResource::NamedResourceSpec

            def initialize: (
              ?discrete_resource_spec: DockerEngineRuby::Node::Description::Resources::GenericResource::DiscreteResourceSpec,
              ?named_resource_spec: DockerEngineRuby::Node::Description::Resources::GenericResource::NamedResourceSpec
            ) -> void

            def to_hash: -> {
              discrete_resource_spec: DockerEngineRuby::Node::Description::Resources::GenericResource::DiscreteResourceSpec,
              named_resource_spec: DockerEngineRuby::Node::Description::Resources::GenericResource::NamedResourceSpec
            }

            type discrete_resource_spec = { kind: String, value: Integer }

            class DiscreteResourceSpec < DockerEngineRuby::Internal::Type::BaseModel
              attr_reader kind: String?

              def kind=: (String) -> String

              attr_reader value: Integer?

              def value=: (Integer) -> Integer

              def initialize: (?kind: String, ?value: Integer) -> void

              def to_hash: -> { kind: String, value: Integer }
            end

            type named_resource_spec = { kind: String, value: String }

            class NamedResourceSpec < DockerEngineRuby::Internal::Type::BaseModel
              attr_reader kind: String?

              def kind=: (String) -> String

              attr_reader value: String?

              def value=: (String) -> String

              def initialize: (?kind: String, ?value: String) -> void

              def to_hash: -> { kind: String, value: String }
            end
          end
        end

        type tls_info =
          {
            cert_issuer_public_key: String,
            cert_issuer_subject: String,
            trust_root: String
          }

        class TlsInfo < DockerEngineRuby::Internal::Type::BaseModel
          attr_reader cert_issuer_public_key: String?

          def cert_issuer_public_key=: (String) -> String

          attr_reader cert_issuer_subject: String?

          def cert_issuer_subject=: (String) -> String

          attr_reader trust_root: String?

          def trust_root=: (String) -> String

          def initialize: (
            ?cert_issuer_public_key: String,
            ?cert_issuer_subject: String,
            ?trust_root: String
          ) -> void

          def to_hash: -> {
            cert_issuer_public_key: String,
            cert_issuer_subject: String,
            trust_root: String
          }
        end
      end

      type manager_status =
        {
          addr: String,
          leader: bool,
          reachability: DockerEngineRuby::Models::Node::ManagerStatus::reachability
        }

      class ManagerStatus < DockerEngineRuby::Internal::Type::BaseModel
        attr_reader addr: String?

        def addr=: (String) -> String

        attr_reader leader: bool?

        def leader=: (bool) -> bool

        attr_reader reachability: DockerEngineRuby::Models::Node::ManagerStatus::reachability?

        def reachability=: (
          DockerEngineRuby::Models::Node::ManagerStatus::reachability
        ) -> DockerEngineRuby::Models::Node::ManagerStatus::reachability

        def initialize: (
          ?addr: String,
          ?leader: bool,
          ?reachability: DockerEngineRuby::Models::Node::ManagerStatus::reachability
        ) -> void

        def to_hash: -> {
          addr: String,
          leader: bool,
          reachability: DockerEngineRuby::Models::Node::ManagerStatus::reachability
        }

        type reachability = :unknown | :unreachable | :reachable

        module Reachability
          extend DockerEngineRuby::Internal::Type::Enum

          UNKNOWN: :unknown
          UNREACHABLE: :unreachable
          REACHABLE: :reachable

          def self?.values: -> ::Array[DockerEngineRuby::Models::Node::ManagerStatus::reachability]
        end
      end

      type status =
        {
          addr: String,
          message: String,
          state: DockerEngineRuby::Models::Node::Status::state
        }

      class Status < DockerEngineRuby::Internal::Type::BaseModel
        attr_reader addr: String?

        def addr=: (String) -> String

        attr_reader message: String?

        def message=: (String) -> String

        attr_reader state: DockerEngineRuby::Models::Node::Status::state?

        def state=: (
          DockerEngineRuby::Models::Node::Status::state
        ) -> DockerEngineRuby::Models::Node::Status::state

        def initialize: (
          ?addr: String,
          ?message: String,
          ?state: DockerEngineRuby::Models::Node::Status::state
        ) -> void

        def to_hash: -> {
          addr: String,
          message: String,
          state: DockerEngineRuby::Models::Node::Status::state
        }

        type state = :unknown | :down | :ready | :disconnected

        module State
          extend DockerEngineRuby::Internal::Type::Enum

          UNKNOWN: :unknown
          DOWN: :down
          READY: :ready
          DISCONNECTED: :disconnected

          def self?.values: -> ::Array[DockerEngineRuby::Models::Node::Status::state]
        end
      end

      type version = { index: Integer }

      class Version < DockerEngineRuby::Internal::Type::BaseModel
        attr_reader index: Integer?

        def index=: (Integer) -> Integer

        def initialize: (?index: Integer) -> void

        def to_hash: -> { index: Integer }
      end
    end
  end
end
