module DockerEngineRuby
  module Models
    type plugin_create_params =
      { name: String, body: DockerEngineRuby::Internal::file_input }
      & DockerEngineRuby::Internal::Type::request_parameters

    class PluginCreateParams < DockerEngineRuby::Internal::Type::BaseModel
      extend DockerEngineRuby::Internal::Type::RequestParameters::Converter
      include DockerEngineRuby::Internal::Type::RequestParameters

      attr_accessor name: String

      attr_accessor body: DockerEngineRuby::Internal::file_input

      def initialize: (
        name: String,
        body: DockerEngineRuby::Internal::file_input,
        ?request_options: DockerEngineRuby::request_opts
      ) -> void

      def to_hash: -> {
        name: String,
        body: DockerEngineRuby::Internal::file_input,
        request_options: DockerEngineRuby::RequestOptions
      }
    end
  end
end
