module DockerEngineRuby
  module Models
    type plugin_push_params =
      { name: String } & DockerEngineRuby::Internal::Type::request_parameters

    class PluginPushParams < DockerEngineRuby::Internal::Type::BaseModel
      extend DockerEngineRuby::Internal::Type::RequestParameters::Converter
      include DockerEngineRuby::Internal::Type::RequestParameters

      attr_accessor name: String

      def initialize: (
        name: String,
        ?request_options: DockerEngineRuby::request_opts
      ) -> void

      def to_hash: -> {
        name: String,
        request_options: DockerEngineRuby::RequestOptions
      }
    end
  end
end
