module DockerEngineRuby
  module Models
    type plugin_set_params =
      { body: ::Array[String] }
      & DockerEngineRuby::Internal::Type::request_parameters

    class PluginSetParams < DockerEngineRuby::Internal::Type::BaseModel
      extend DockerEngineRuby::Internal::Type::RequestParameters::Converter
      include DockerEngineRuby::Internal::Type::RequestParameters

      attr_reader body: ::Array[String]?

      def body=: (::Array[String]) -> ::Array[String]

      def initialize: (
        ?body: ::Array[String],
        ?request_options: DockerEngineRuby::request_opts
      ) -> void

      def to_hash: -> {
        body: ::Array[String],
        request_options: DockerEngineRuby::RequestOptions
      }
    end
  end
end
