module DockerEngineRuby
  module Models
    type secret_inspect_params =
      { id: String } & DockerEngineRuby::Internal::Type::request_parameters

    class SecretInspectParams < DockerEngineRuby::Internal::Type::BaseModel
      extend DockerEngineRuby::Internal::Type::RequestParameters::Converter
      include DockerEngineRuby::Internal::Type::RequestParameters

      attr_accessor id: String

      def initialize: (
        id: String,
        ?request_options: DockerEngineRuby::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        request_options: DockerEngineRuby::RequestOptions
      }
    end
  end
end
