module DockerEngineRuby
  module Models
    type secret_spec =
      {
        data: String,
        driver: DockerEngineRuby::SecretSpec::Driver,
        labels: ::Hash[Symbol, String],
        name: String,
        templating: DockerEngineRuby::SecretSpec::Templating
      }

    class SecretSpec < DockerEngineRuby::Internal::Type::BaseModel
      attr_reader data: String?

      def data=: (String) -> String

      attr_reader driver: DockerEngineRuby::SecretSpec::Driver?

      def driver=: (
        DockerEngineRuby::SecretSpec::Driver
      ) -> DockerEngineRuby::SecretSpec::Driver

      attr_reader labels: ::Hash[Symbol, String]?

      def labels=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader templating: DockerEngineRuby::SecretSpec::Templating?

      def templating=: (
        DockerEngineRuby::SecretSpec::Templating
      ) -> DockerEngineRuby::SecretSpec::Templating

      def initialize: (
        ?data: String,
        ?driver: DockerEngineRuby::SecretSpec::Driver,
        ?labels: ::Hash[Symbol, String],
        ?name: String,
        ?templating: DockerEngineRuby::SecretSpec::Templating
      ) -> void

      def to_hash: -> {
        data: String,
        driver: DockerEngineRuby::SecretSpec::Driver,
        labels: ::Hash[Symbol, String],
        name: String,
        templating: DockerEngineRuby::SecretSpec::Templating
      }

      type driver = { name: String, options: ::Hash[Symbol, String] }

      class Driver < DockerEngineRuby::Internal::Type::BaseModel
        attr_accessor name: String

        attr_reader options: ::Hash[Symbol, String]?

        def options=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        def initialize: (name: String, ?options: ::Hash[Symbol, String]) -> void

        def to_hash: -> { name: String, options: ::Hash[Symbol, String] }
      end

      type templating = { name: String, options: ::Hash[Symbol, String] }

      class Templating < DockerEngineRuby::Internal::Type::BaseModel
        attr_accessor name: String

        attr_reader options: ::Hash[Symbol, String]?

        def options=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        def initialize: (name: String, ?options: ::Hash[Symbol, String]) -> void

        def to_hash: -> { name: String, options: ::Hash[Symbol, String] }
      end
    end
  end
end
