module DockerEngineRuby
  module Models
    type secret_update_params =
      { id: String, version: Integer }
      & DockerEngineRuby::Internal::Type::request_parameters

    class SecretUpdateParams < DockerEngineRuby::Internal::Type::BaseModel
      extend DockerEngineRuby::Internal::Type::RequestParameters::Converter
      include DockerEngineRuby::Internal::Type::RequestParameters

      attr_accessor id: String

      attr_accessor version: Integer

      def initialize: (
        id: String,
        version: Integer,
        ?request_options: DockerEngineRuby::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        version: Integer,
        request_options: DockerEngineRuby::RequestOptions
      }
    end
  end
end
