module DockerEngineRuby
  module Models
    type secret =
      {
        created_at: String,
        id: String,
        spec: DockerEngineRuby::Spec,
        updated_at: String,
        version: DockerEngineRuby::Secret::Version
      }

    class Secret < DockerEngineRuby::Internal::Type::BaseModel
      attr_reader created_at: String?

      def created_at=: (String) -> String

      attr_reader id: String?

      def id=: (String) -> String

      attr_reader spec: DockerEngineRuby::Spec?

      def spec=: (DockerEngineRuby::Spec) -> DockerEngineRuby::Spec

      attr_reader updated_at: String?

      def updated_at=: (String) -> String

      attr_reader version: DockerEngineRuby::Secret::Version?

      def version=: (
        DockerEngineRuby::Secret::Version
      ) -> DockerEngineRuby::Secret::Version

      def initialize: (
        ?created_at: String,
        ?id: String,
        ?spec: DockerEngineRuby::Spec,
        ?updated_at: String,
        ?version: DockerEngineRuby::Secret::Version
      ) -> void

      def to_hash: -> {
        created_at: String,
        id: String,
        spec: DockerEngineRuby::Spec,
        updated_at: String,
        version: DockerEngineRuby::Secret::Version
      }

      type version = { index: Integer }

      class Version < DockerEngineRuby::Internal::Type::BaseModel
        attr_reader index: Integer?

        def index=: (Integer) -> Integer

        def initialize: (?index: Integer) -> void

        def to_hash: -> { index: Integer }
      end
    end
  end
end
