module DockerEngineRuby
  module Models
    type secret_spec =
      {
        data: String,
        driver: DockerEngineRuby::SecretSpec::Driver,
        labels: top,
        name: String,
        templating: DockerEngineRuby::SecretSpec::Templating
      }

    class SecretSpec < DockerEngineRuby::Internal::Type::BaseModel
      attr_reader data: String?

      def data=: (String) -> String

      attr_reader driver: DockerEngineRuby::SecretSpec::Driver?

      def driver=: (
        DockerEngineRuby::SecretSpec::Driver
      ) -> DockerEngineRuby::SecretSpec::Driver

      attr_reader labels: top?

      def labels=: (top) -> top

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader templating: DockerEngineRuby::SecretSpec::Templating?

      def templating=: (
        DockerEngineRuby::SecretSpec::Templating
      ) -> DockerEngineRuby::SecretSpec::Templating

      def initialize: (
        ?data: String,
        ?driver: DockerEngineRuby::SecretSpec::Driver,
        ?labels: top,
        ?name: String,
        ?templating: DockerEngineRuby::SecretSpec::Templating
      ) -> void

      def to_hash: -> {
        data: String,
        driver: DockerEngineRuby::SecretSpec::Driver,
        labels: top,
        name: String,
        templating: DockerEngineRuby::SecretSpec::Templating
      }

      type driver = { name: String, options: top }

      class Driver < DockerEngineRuby::Internal::Type::BaseModel
        attr_accessor name: String

        attr_reader options: top?

        def options=: (top) -> top

        def initialize: (name: String, ?options: top) -> void

        def to_hash: -> { name: String, options: top }
      end

      type templating = { name: String, options: top }

      class Templating < DockerEngineRuby::Internal::Type::BaseModel
        attr_accessor name: String

        attr_reader options: top?

        def options=: (top) -> top

        def initialize: (name: String, ?options: top) -> void

        def to_hash: -> { name: String, options: top }
      end
    end
  end
end
