module DockerEngineRuby
  module Models
    type secret_create_params =
      { spec: DockerEngineRuby::SecretSpec }
      & DockerEngineRuby::Internal::Type::request_parameters

    class SecretCreateParams < DockerEngineRuby::Internal::Type::BaseModel
      extend DockerEngineRuby::Internal::Type::RequestParameters::Converter
      include DockerEngineRuby::Internal::Type::RequestParameters

      attr_accessor spec: DockerEngineRuby::SecretSpec

      def initialize: (?request_options: DockerEngineRuby::request_opts) -> void

      def to_hash: -> { request_options: DockerEngineRuby::RequestOptions }
    end
  end
end
