module DockerEngineRuby
  module Models
    type service_update_response = { warnings: ::Array[String] }

    class ServiceUpdateResponse < DockerEngineRuby::Internal::Type::BaseModel
      attr_reader warnings: ::Array[String]?

      def warnings=: (::Array[String]) -> ::Array[String]

      def initialize: (?warnings: ::Array[String]) -> void

      def to_hash: -> { warnings: ::Array[String] }
    end
  end
end
