module DockerEngineRuby
  module Models
    type service_update_params =
      {
        version: Integer,
        spec: DockerEngineRuby::ServiceUpdateParams::Spec,
        registry_auth_from: DockerEngineRuby::Models::ServiceUpdateParams::registry_auth_from,
        rollback: String,
        x_registry_auth: String
      }
      & DockerEngineRuby::Internal::Type::request_parameters

    class ServiceUpdateParams < DockerEngineRuby::Internal::Type::BaseModel
      extend DockerEngineRuby::Internal::Type::RequestParameters::Converter
      include DockerEngineRuby::Internal::Type::RequestParameters

      attr_accessor version: Integer

      attr_accessor spec: DockerEngineRuby::ServiceUpdateParams::Spec

      attr_reader registry_auth_from: DockerEngineRuby::Models::ServiceUpdateParams::registry_auth_from?

      def registry_auth_from=: (
        DockerEngineRuby::Models::ServiceUpdateParams::registry_auth_from
      ) -> DockerEngineRuby::Models::ServiceUpdateParams::registry_auth_from

      attr_reader rollback: String?

      def rollback=: (String) -> String

      attr_reader x_registry_auth: String?

      def x_registry_auth=: (String) -> String

      def initialize: (
        version: Integer,
        spec: DockerEngineRuby::ServiceUpdateParams::Spec,
        ?registry_auth_from: DockerEngineRuby::Models::ServiceUpdateParams::registry_auth_from,
        ?rollback: String,
        ?x_registry_auth: String,
        ?request_options: DockerEngineRuby::request_opts
      ) -> void

      def to_hash: -> {
        version: Integer,
        spec: DockerEngineRuby::ServiceUpdateParams::Spec,
        registry_auth_from: DockerEngineRuby::Models::ServiceUpdateParams::registry_auth_from,
        rollback: String,
        x_registry_auth: String,
        request_options: DockerEngineRuby::RequestOptions
      }

      type spec = {  }

      class Spec < DockerEngineRuby::Models::Spec
        def initialize: -> void

        def to_hash: -> {  }
      end

      type registry_auth_from = :spec | :"previous-spec"

      module RegistryAuthFrom
        extend DockerEngineRuby::Internal::Type::Enum

        SPEC: :spec
        PREVIOUS_SPEC: :"previous-spec"

        def self?.values: -> ::Array[DockerEngineRuby::Models::ServiceUpdateParams::registry_auth_from]
      end
    end
  end
end
