module DockerEngineRuby
  module Models
    type swarm_join_params =
      {
        advertise_addr: String,
        data_path_addr: String,
        join_token: String,
        listen_addr: String,
        remote_addrs: ::Array[String]
      }
      & DockerEngineRuby::Internal::Type::request_parameters

    class SwarmJoinParams < DockerEngineRuby::Internal::Type::BaseModel
      extend DockerEngineRuby::Internal::Type::RequestParameters::Converter
      include DockerEngineRuby::Internal::Type::RequestParameters

      attr_reader advertise_addr: String?

      def advertise_addr=: (String) -> String

      attr_reader data_path_addr: String?

      def data_path_addr=: (String) -> String

      attr_reader join_token: String?

      def join_token=: (String) -> String

      attr_reader listen_addr: String?

      def listen_addr=: (String) -> String

      attr_reader remote_addrs: ::Array[String]?

      def remote_addrs=: (::Array[String]) -> ::Array[String]

      def initialize: (
        ?advertise_addr: String,
        ?data_path_addr: String,
        ?join_token: String,
        ?listen_addr: String,
        ?remote_addrs: ::Array[String],
        ?request_options: DockerEngineRuby::request_opts
      ) -> void

      def to_hash: -> {
        advertise_addr: String,
        data_path_addr: String,
        join_token: String,
        listen_addr: String,
        remote_addrs: ::Array[String],
        request_options: DockerEngineRuby::RequestOptions
      }
    end
  end
end
