module DockerEngineRuby
  module Models
    type system_data_usage_params =
      {
        type: DockerEngineRuby::Models::SystemDataUsageParams::type_,
        verbose: bool
      }
      & DockerEngineRuby::Internal::Type::request_parameters

    class SystemDataUsageParams < DockerEngineRuby::Internal::Type::BaseModel
      extend DockerEngineRuby::Internal::Type::RequestParameters::Converter
      include DockerEngineRuby::Internal::Type::RequestParameters

      attr_reader type: DockerEngineRuby::Models::SystemDataUsageParams::type_?

      def type=: (
        DockerEngineRuby::Models::SystemDataUsageParams::type_
      ) -> DockerEngineRuby::Models::SystemDataUsageParams::type_

      attr_reader verbose: bool?

      def verbose=: (bool) -> bool

      def initialize: (
        ?type: DockerEngineRuby::Models::SystemDataUsageParams::type_,
        ?verbose: bool,
        ?request_options: DockerEngineRuby::request_opts
      ) -> void

      def to_hash: -> {
        type: DockerEngineRuby::Models::SystemDataUsageParams::type_,
        verbose: bool,
        request_options: DockerEngineRuby::RequestOptions
      }

      type type_ =
        :container
        | :image
        | :volume
        | ::Array[DockerEngineRuby::Models::SystemDataUsageParams::Type::union_member1]

      module Type
        extend DockerEngineRuby::Internal::Type::Union

        type union_member1 = :"build-cache"

        module UnionMember1
          extend DockerEngineRuby::Internal::Type::Enum

          BUILD_CACHE: :"build-cache"

          def self?.values: -> ::Array[DockerEngineRuby::Models::SystemDataUsageParams::Type::union_member1]
        end

        def self?.variants: -> ::Array[DockerEngineRuby::Models::SystemDataUsageParams::type_]

        CONTAINER: :container
        IMAGE: :image
        VOLUME: :volume

        UnionMember1Array: DockerEngineRuby::Internal::Type::Converter
      end
    end
  end
end
