module DockerEngineRuby
  module Models
    type task =
      {
        assigned_generic_resources: ::Array[DockerEngineRuby::Task::AssignedGenericResource],
        created_at: Time,
        desired_state: DockerEngineRuby::Models::Task::desired_state,
        id: String,
        job_iteration: DockerEngineRuby::Task::JobIteration,
        labels: top,
        name: String,
        node_id: String,
        service_id: String,
        slot: Integer,
        spec: DockerEngineRuby::TaskSpec,
        status: DockerEngineRuby::Task::Status,
        updated_at: Time,
        version: DockerEngineRuby::Task::Version
      }

    class Task < DockerEngineRuby::Internal::Type::BaseModel
      attr_reader assigned_generic_resources: ::Array[DockerEngineRuby::Task::AssignedGenericResource]?

      def assigned_generic_resources=: (
        ::Array[DockerEngineRuby::Task::AssignedGenericResource]
      ) -> ::Array[DockerEngineRuby::Task::AssignedGenericResource]

      attr_reader created_at: Time?

      def created_at=: (Time) -> Time

      attr_reader desired_state: DockerEngineRuby::Models::Task::desired_state?

      def desired_state=: (
        DockerEngineRuby::Models::Task::desired_state
      ) -> DockerEngineRuby::Models::Task::desired_state

      attr_reader id: String?

      def id=: (String) -> String

      attr_reader job_iteration: DockerEngineRuby::Task::JobIteration?

      def job_iteration=: (
        DockerEngineRuby::Task::JobIteration
      ) -> DockerEngineRuby::Task::JobIteration

      attr_reader labels: top?

      def labels=: (top) -> top

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader node_id: String?

      def node_id=: (String) -> String

      attr_reader service_id: String?

      def service_id=: (String) -> String

      attr_reader slot: Integer?

      def slot=: (Integer) -> Integer

      attr_reader spec: DockerEngineRuby::TaskSpec?

      def spec=: (DockerEngineRuby::TaskSpec) -> DockerEngineRuby::TaskSpec

      attr_reader status: DockerEngineRuby::Task::Status?

      def status=: (
        DockerEngineRuby::Task::Status
      ) -> DockerEngineRuby::Task::Status

      attr_reader updated_at: Time?

      def updated_at=: (Time) -> Time

      attr_reader version: DockerEngineRuby::Task::Version?

      def version=: (
        DockerEngineRuby::Task::Version
      ) -> DockerEngineRuby::Task::Version

      def initialize: (
        ?assigned_generic_resources: ::Array[DockerEngineRuby::Task::AssignedGenericResource],
        ?created_at: Time,
        ?desired_state: DockerEngineRuby::Models::Task::desired_state,
        ?id: String,
        ?job_iteration: DockerEngineRuby::Task::JobIteration,
        ?labels: top,
        ?name: String,
        ?node_id: String,
        ?service_id: String,
        ?slot: Integer,
        ?spec: DockerEngineRuby::TaskSpec,
        ?status: DockerEngineRuby::Task::Status,
        ?updated_at: Time,
        ?version: DockerEngineRuby::Task::Version
      ) -> void

      def to_hash: -> {
        assigned_generic_resources: ::Array[DockerEngineRuby::Task::AssignedGenericResource],
        created_at: Time,
        desired_state: DockerEngineRuby::Models::Task::desired_state,
        id: String,
        job_iteration: DockerEngineRuby::Task::JobIteration,
        labels: top,
        name: String,
        node_id: String,
        service_id: String,
        slot: Integer,
        spec: DockerEngineRuby::TaskSpec,
        status: DockerEngineRuby::Task::Status,
        updated_at: Time,
        version: DockerEngineRuby::Task::Version
      }

      type assigned_generic_resource =
        {
          discrete_resource_spec: DockerEngineRuby::Task::AssignedGenericResource::DiscreteResourceSpec,
          named_resource_spec: DockerEngineRuby::Task::AssignedGenericResource::NamedResourceSpec
        }

      class AssignedGenericResource < DockerEngineRuby::Internal::Type::BaseModel
        attr_reader discrete_resource_spec: DockerEngineRuby::Task::AssignedGenericResource::DiscreteResourceSpec?

        def discrete_resource_spec=: (
          DockerEngineRuby::Task::AssignedGenericResource::DiscreteResourceSpec
        ) -> DockerEngineRuby::Task::AssignedGenericResource::DiscreteResourceSpec

        attr_reader named_resource_spec: DockerEngineRuby::Task::AssignedGenericResource::NamedResourceSpec?

        def named_resource_spec=: (
          DockerEngineRuby::Task::AssignedGenericResource::NamedResourceSpec
        ) -> DockerEngineRuby::Task::AssignedGenericResource::NamedResourceSpec

        def initialize: (
          ?discrete_resource_spec: DockerEngineRuby::Task::AssignedGenericResource::DiscreteResourceSpec,
          ?named_resource_spec: DockerEngineRuby::Task::AssignedGenericResource::NamedResourceSpec
        ) -> void

        def to_hash: -> {
          discrete_resource_spec: DockerEngineRuby::Task::AssignedGenericResource::DiscreteResourceSpec,
          named_resource_spec: DockerEngineRuby::Task::AssignedGenericResource::NamedResourceSpec
        }

        type discrete_resource_spec = { kind: String, value: Integer }

        class DiscreteResourceSpec < DockerEngineRuby::Internal::Type::BaseModel
          attr_reader kind: String?

          def kind=: (String) -> String

          attr_reader value: Integer?

          def value=: (Integer) -> Integer

          def initialize: (?kind: String, ?value: Integer) -> void

          def to_hash: -> { kind: String, value: Integer }
        end

        type named_resource_spec = { kind: String, value: String }

        class NamedResourceSpec < DockerEngineRuby::Internal::Type::BaseModel
          attr_reader kind: String?

          def kind=: (String) -> String

          attr_reader value: String?

          def value=: (String) -> String

          def initialize: (?kind: String, ?value: String) -> void

          def to_hash: -> { kind: String, value: String }
        end
      end

      type desired_state =
        :new
        | :allocated
        | :pending
        | :assigned
        | :accepted
        | :preparing
        | :ready
        | :starting
        | :running
        | :complete
        | :shutdown
        | :failed
        | :rejected
        | :remove
        | :orphaned

      module DesiredState
        extend DockerEngineRuby::Internal::Type::Enum

        NEW: :new
        ALLOCATED: :allocated
        PENDING: :pending
        ASSIGNED: :assigned
        ACCEPTED: :accepted
        PREPARING: :preparing
        READY: :ready
        STARTING: :starting
        RUNNING: :running
        COMPLETE: :complete
        SHUTDOWN: :shutdown
        FAILED: :failed
        REJECTED: :rejected
        REMOVE: :remove
        ORPHANED: :orphaned

        def self?.values: -> ::Array[DockerEngineRuby::Models::Task::desired_state]
      end

      type job_iteration = { index: Integer }

      class JobIteration < DockerEngineRuby::Internal::Type::BaseModel
        attr_reader index: Integer?

        def index=: (Integer) -> Integer

        def initialize: (?index: Integer) -> void

        def to_hash: -> { index: Integer }
      end

      type status =
        {
          container_status: DockerEngineRuby::Task::Status::ContainerStatus,
          err: String,
          message: String,
          port_status: DockerEngineRuby::Task::Status::PortStatus,
          state: DockerEngineRuby::Models::Task::Status::state,
          timestamp: Time
        }

      class Status < DockerEngineRuby::Internal::Type::BaseModel
        attr_reader container_status: DockerEngineRuby::Task::Status::ContainerStatus?

        def container_status=: (
          DockerEngineRuby::Task::Status::ContainerStatus
        ) -> DockerEngineRuby::Task::Status::ContainerStatus

        attr_reader err: String?

        def err=: (String) -> String

        attr_reader message: String?

        def message=: (String) -> String

        attr_reader port_status: DockerEngineRuby::Task::Status::PortStatus?

        def port_status=: (
          DockerEngineRuby::Task::Status::PortStatus
        ) -> DockerEngineRuby::Task::Status::PortStatus

        attr_reader state: DockerEngineRuby::Models::Task::Status::state?

        def state=: (
          DockerEngineRuby::Models::Task::Status::state
        ) -> DockerEngineRuby::Models::Task::Status::state

        attr_reader timestamp: Time?

        def timestamp=: (Time) -> Time

        def initialize: (
          ?container_status: DockerEngineRuby::Task::Status::ContainerStatus,
          ?err: String,
          ?message: String,
          ?port_status: DockerEngineRuby::Task::Status::PortStatus,
          ?state: DockerEngineRuby::Models::Task::Status::state,
          ?timestamp: Time
        ) -> void

        def to_hash: -> {
          container_status: DockerEngineRuby::Task::Status::ContainerStatus,
          err: String,
          message: String,
          port_status: DockerEngineRuby::Task::Status::PortStatus,
          state: DockerEngineRuby::Models::Task::Status::state,
          timestamp: Time
        }

        type container_status =
          { container_id: String, exit_code: Integer, pid: Integer }

        class ContainerStatus < DockerEngineRuby::Internal::Type::BaseModel
          attr_reader container_id: String?

          def container_id=: (String) -> String

          attr_reader exit_code: Integer?

          def exit_code=: (Integer) -> Integer

          attr_reader pid: Integer?

          def pid=: (Integer) -> Integer

          def initialize: (
            ?container_id: String,
            ?exit_code: Integer,
            ?pid: Integer
          ) -> void

          def to_hash: -> {
            container_id: String,
            exit_code: Integer,
            pid: Integer
          }
        end

        type port_status =
          { ports: ::Array[DockerEngineRuby::Task::Status::PortStatus::Port] }

        class PortStatus < DockerEngineRuby::Internal::Type::BaseModel
          attr_reader ports: ::Array[DockerEngineRuby::Task::Status::PortStatus::Port]?

          def ports=: (
            ::Array[DockerEngineRuby::Task::Status::PortStatus::Port]
          ) -> ::Array[DockerEngineRuby::Task::Status::PortStatus::Port]

          def initialize: (
            ?ports: ::Array[DockerEngineRuby::Task::Status::PortStatus::Port]
          ) -> void

          def to_hash: -> {
            ports: ::Array[DockerEngineRuby::Task::Status::PortStatus::Port]
          }

          type port =
            {
              name: String,
              protocol: DockerEngineRuby::Models::Task::Status::PortStatus::Port::protocol,
              published_port: Integer,
              publish_mode: DockerEngineRuby::Models::Task::Status::PortStatus::Port::publish_mode,
              target_port: Integer
            }

          class Port < DockerEngineRuby::Internal::Type::BaseModel
            attr_reader name: String?

            def name=: (String) -> String

            attr_reader protocol: DockerEngineRuby::Models::Task::Status::PortStatus::Port::protocol?

            def protocol=: (
              DockerEngineRuby::Models::Task::Status::PortStatus::Port::protocol
            ) -> DockerEngineRuby::Models::Task::Status::PortStatus::Port::protocol

            attr_reader published_port: Integer?

            def published_port=: (Integer) -> Integer

            attr_reader publish_mode: DockerEngineRuby::Models::Task::Status::PortStatus::Port::publish_mode?

            def publish_mode=: (
              DockerEngineRuby::Models::Task::Status::PortStatus::Port::publish_mode
            ) -> DockerEngineRuby::Models::Task::Status::PortStatus::Port::publish_mode

            attr_reader target_port: Integer?

            def target_port=: (Integer) -> Integer

            def initialize: (
              ?name: String,
              ?protocol: DockerEngineRuby::Models::Task::Status::PortStatus::Port::protocol,
              ?published_port: Integer,
              ?publish_mode: DockerEngineRuby::Models::Task::Status::PortStatus::Port::publish_mode,
              ?target_port: Integer
            ) -> void

            def to_hash: -> {
              name: String,
              protocol: DockerEngineRuby::Models::Task::Status::PortStatus::Port::protocol,
              published_port: Integer,
              publish_mode: DockerEngineRuby::Models::Task::Status::PortStatus::Port::publish_mode,
              target_port: Integer
            }

            type protocol = :tcp | :udp | :sctp

            module Protocol
              extend DockerEngineRuby::Internal::Type::Enum

              TCP: :tcp
              UDP: :udp
              SCTP: :sctp

              def self?.values: -> ::Array[DockerEngineRuby::Models::Task::Status::PortStatus::Port::protocol]
            end

            type publish_mode = :ingress | :host

            module PublishMode
              extend DockerEngineRuby::Internal::Type::Enum

              INGRESS: :ingress
              HOST: :host

              def self?.values: -> ::Array[DockerEngineRuby::Models::Task::Status::PortStatus::Port::publish_mode]
            end
          end
        end

        type state =
          :new
          | :allocated
          | :pending
          | :assigned
          | :accepted
          | :preparing
          | :ready
          | :starting
          | :running
          | :complete
          | :shutdown
          | :failed
          | :rejected
          | :remove
          | :orphaned

        module State
          extend DockerEngineRuby::Internal::Type::Enum

          NEW: :new
          ALLOCATED: :allocated
          PENDING: :pending
          ASSIGNED: :assigned
          ACCEPTED: :accepted
          PREPARING: :preparing
          READY: :ready
          STARTING: :starting
          RUNNING: :running
          COMPLETE: :complete
          SHUTDOWN: :shutdown
          FAILED: :failed
          REJECTED: :rejected
          REMOVE: :remove
          ORPHANED: :orphaned

          def self?.values: -> ::Array[DockerEngineRuby::Models::Task::Status::state]
        end
      end

      type version = { index: Integer }

      class Version < DockerEngineRuby::Internal::Type::BaseModel
        attr_reader index: Integer?

        def index=: (Integer) -> Integer

        def initialize: (?index: Integer) -> void

        def to_hash: -> { index: Integer }
      end
    end
  end
end
