module DockerEngineRuby
  module Models
    type version =
      {
        api_version: String,
        arch: String,
        build_time: String,
        components: ::Array[DockerEngineRuby::Version::Component],
        experimental: bool,
        git_commit: String,
        go_version: String,
        kernel_version: String,
        min_api_version: String,
        os: String,
        platform: DockerEngineRuby::Version::Platform,
        version: String
      }

    class Version < DockerEngineRuby::Internal::Type::BaseModel
      attr_reader api_version: String?

      def api_version=: (String) -> String

      attr_reader arch: String?

      def arch=: (String) -> String

      attr_reader build_time: String?

      def build_time=: (String) -> String

      attr_reader components: ::Array[DockerEngineRuby::Version::Component]?

      def components=: (
        ::Array[DockerEngineRuby::Version::Component]
      ) -> ::Array[DockerEngineRuby::Version::Component]

      attr_reader experimental: bool?

      def experimental=: (bool) -> bool

      attr_reader git_commit: String?

      def git_commit=: (String) -> String

      attr_reader go_version: String?

      def go_version=: (String) -> String

      attr_reader kernel_version: String?

      def kernel_version=: (String) -> String

      attr_reader min_api_version: String?

      def min_api_version=: (String) -> String

      attr_reader os: String?

      def os=: (String) -> String

      attr_reader platform: DockerEngineRuby::Version::Platform?

      def platform=: (
        DockerEngineRuby::Version::Platform
      ) -> DockerEngineRuby::Version::Platform

      attr_reader version: String?

      def version=: (String) -> String

      def initialize: (
        ?api_version: String,
        ?arch: String,
        ?build_time: String,
        ?components: ::Array[DockerEngineRuby::Version::Component],
        ?experimental: bool,
        ?git_commit: String,
        ?go_version: String,
        ?kernel_version: String,
        ?min_api_version: String,
        ?os: String,
        ?platform: DockerEngineRuby::Version::Platform,
        ?version: String
      ) -> void

      def to_hash: -> {
        api_version: String,
        arch: String,
        build_time: String,
        components: ::Array[DockerEngineRuby::Version::Component],
        experimental: bool,
        git_commit: String,
        go_version: String,
        kernel_version: String,
        min_api_version: String,
        os: String,
        platform: DockerEngineRuby::Version::Platform,
        version: String
      }

      type component =
        { name: String, version: String, details: ::Hash[Symbol, top]? }

      class Component < DockerEngineRuby::Internal::Type::BaseModel
        attr_accessor name: String

        attr_accessor version: String

        attr_accessor details: ::Hash[Symbol, top]?

        def initialize: (
          name: String,
          version: String,
          ?details: ::Hash[Symbol, top]?
        ) -> void

        def to_hash: -> {
          name: String,
          version: String,
          details: ::Hash[Symbol, top]?
        }
      end

      type platform = { name: String }

      class Platform < DockerEngineRuby::Internal::Type::BaseModel
        attr_accessor name: String

        def initialize: (name: String) -> void

        def to_hash: -> { name: String }
      end
    end
  end
end
