module DockerEngineRuby
  module Internal
    extend DockerEngineRuby::Internal::Util::SorbetRuntimeSupport

    type file_input =
      Pathname | StringIO | IO | String | DockerEngineRuby::FilePart

    OMIT: Object
  end
end
