# frozen_string_literal: true

# Standard libraries.
# rubocop:disable Lint/RedundantRequireStatement
require "English"
require "base64"
require "cgi"
require "date"
require "erb"
require "etc"
require "json"
require "net/http"
require "openssl"
require "pathname"
require "rbconfig"
require "securerandom"
require "set"
require "stringio"
require "time"
require "uri"
# rubocop:enable Lint/RedundantRequireStatement

# We already ship the preferred sorbet manifests in the package itself.
# `tapioca` currently does not offer us a way to opt out of unnecessary compilation.
if Object.const_defined?(:Tapioca) &&
   caller.chain([$PROGRAM_NAME]).chain(ARGV).any?(/tapioca/) &&
   ARGV.none?(/dsl/)
  return
end

# Gems.
require "connection_pool"

# Package files.
require_relative "docker_engine/version"
require_relative "docker_engine/internal/util"
require_relative "docker_engine/internal/type/converter"
require_relative "docker_engine/internal/type/unknown"
require_relative "docker_engine/internal/type/boolean"
require_relative "docker_engine/internal/type/file_input"
require_relative "docker_engine/internal/type/enum"
require_relative "docker_engine/internal/type/union"
require_relative "docker_engine/internal/type/array_of"
require_relative "docker_engine/internal/type/hash_of"
require_relative "docker_engine/internal/type/base_model"
require_relative "docker_engine/internal/type/base_page"
require_relative "docker_engine/internal/type/request_parameters"
require_relative "docker_engine/internal"
require_relative "docker_engine/request_options"
require_relative "docker_engine/file_part"
require_relative "docker_engine/errors"
require_relative "docker_engine/internal/transport/base_client"
require_relative "docker_engine/internal/transport/pooled_net_requester"
require_relative "docker_engine/client"
require_relative "docker_engine/models/config"
require_relative "docker_engine/models/network"
require_relative "docker_engine/models/spec"
require_relative "docker_engine/models/create_request"
require_relative "docker_engine/models/auth_login_params"
require_relative "docker_engine/models/auth_response"
require_relative "docker_engine/models/container"
require_relative "docker_engine/models/container_create_params"
require_relative "docker_engine/models/container_delete_params"
require_relative "docker_engine/models/container_inspect_params"
require_relative "docker_engine/models/container_kill_params"
require_relative "docker_engine/models/container_list_params"
require_relative "docker_engine/models/container_list_response"
require_relative "docker_engine/models/container_logs_params"
require_relative "docker_engine/models/container_start_params"
require_relative "docker_engine/models/container_stop_params"
require_relative "docker_engine/models/create_response"
require_relative "docker_engine/models/error"
require_relative "docker_engine/models/image"
require_relative "docker_engine/models/image_delete_params"
require_relative "docker_engine/models/image_delete_response"
require_relative "docker_engine/models/image_inspect_params"
require_relative "docker_engine/models/image_list_params"
require_relative "docker_engine/models/image_list_response"
require_relative "docker_engine/models/image_pull_params"
require_relative "docker_engine/models/network_create_params"
require_relative "docker_engine/models/network_create_response"
require_relative "docker_engine/models/network_delete_params"
require_relative "docker_engine/models/network_inspect_params"
require_relative "docker_engine/models/network_inspect_response"
require_relative "docker_engine/models/network_list_params"
require_relative "docker_engine/models/network_list_response"
require_relative "docker_engine/models/service"
require_relative "docker_engine/models/service_create_params"
require_relative "docker_engine/models/service_create_response"
require_relative "docker_engine/models/service_delete_params"
require_relative "docker_engine/models/service_inspect_params"
require_relative "docker_engine/models/service_list_params"
require_relative "docker_engine/models/service_list_response"
require_relative "docker_engine/models/summary"
require_relative "docker_engine/models/system_info_params"
require_relative "docker_engine/models/system_info_response"
require_relative "docker_engine/models/system_ping_params"
require_relative "docker_engine/models/system_ping_response"
require_relative "docker_engine/models/system_version_params"
require_relative "docker_engine/models/system_version_response"
require_relative "docker_engine/models/volume"
require_relative "docker_engine/models/volume_create_params"
require_relative "docker_engine/models/volume_delete_params"
require_relative "docker_engine/models/volume_inspect_params"
require_relative "docker_engine/models/volume_list_params"
require_relative "docker_engine/models/volume_list_response"
require_relative "docker_engine/models"
require_relative "docker_engine/resources/auth"
require_relative "docker_engine/resources/containers"
require_relative "docker_engine/resources/images"
require_relative "docker_engine/resources/networks"
require_relative "docker_engine/resources/services"
require_relative "docker_engine/resources/system"
require_relative "docker_engine/resources/volumes"
