module Docker
  module Resources
    class System
      def info: (
        ?request_options: Docker::request_opts
      ) -> Docker::Models::SystemInfoResponse

      def ping: (?request_options: Docker::request_opts) -> String

      def version: (
        ?request_options: Docker::request_opts
      ) -> Docker::Models::SystemVersionResponse

      def initialize: (client: Docker::Client) -> void
    end
  end
end
