module DockerEngine
  module Resources
    class Configs
      def create: (
        ?spec: DockerEngine::ConfigCreateParams::Spec,
        ?request_options: DockerEngine::request_opts
      ) -> DockerEngine::Models::ConfigCreateResponse

      def update: (
        String id,
        version: Integer,
        ?spec: DockerEngine::Spec,
        ?request_options: DockerEngine::request_opts
      ) -> nil

      def list: (
        ?filters: String,
        ?request_options: DockerEngine::request_opts
      ) -> DockerEngine::Models::config_list_response

      def delete: (
        String id,
        ?request_options: DockerEngine::request_opts
      ) -> nil

      def inspect_: (
        String id,
        ?request_options: DockerEngine::request_opts
      ) -> DockerEngine::Config

      def initialize: (client: DockerEngine::Client) -> void
    end
  end
end
