module DockerEngine
  module Resources
    class Containers
      def create: (
        config: DockerEngine::ContainerCreateParams::Config,
        ?name: String,
        ?platform: String,
        ?request_options: DockerEngine::request_opts
      ) -> DockerEngine::CreateResponse

      def list: (
        ?all: bool,
        ?filters: String,
        ?limit: Integer,
        ?size: bool,
        ?request_options: DockerEngine::request_opts
      ) -> DockerEngine::Models::container_list_response

      def delete: (
        String id,
        ?force: bool,
        ?link: bool,
        ?v: bool,
        ?request_options: DockerEngine::request_opts
      ) -> nil

      def inspect_: (
        String id,
        ?size: bool,
        ?request_options: DockerEngine::request_opts
      ) -> DockerEngine::Container

      def kill: (
        String id,
        ?signal: String,
        ?request_options: DockerEngine::request_opts
      ) -> nil

      def logs: (
        String id,
        ?follow: bool,
        ?since: Integer,
        ?stderr: bool,
        ?stdout: bool,
        ?tail: String,
        ?timestamps: bool,
        ?until_: Integer,
        ?request_options: DockerEngine::request_opts
      ) -> StringIO

      def start: (
        String id,
        ?detach_keys: String,
        ?request_options: DockerEngine::request_opts
      ) -> nil

      def stop: (
        String id,
        ?signal: String,
        ?t: Integer,
        ?request_options: DockerEngine::request_opts
      ) -> nil

      def initialize: (client: DockerEngine::Client) -> void
    end
  end
end
