module DockerEngine
  module Resources
    class Networks
      def create: (
        name: String,
        ?attachable: bool,
        ?config_from: DockerEngine::NetworkCreateParams::ConfigFrom,
        ?config_only: bool,
        ?driver: String,
        ?enable_i_pv4: bool,
        ?enable_i_pv6: bool,
        ?ingress: bool,
        ?internal: bool,
        ?ipam: DockerEngine::NetworkCreateParams::Ipam,
        ?labels: ::Hash[Symbol, String],
        ?options: ::Hash[Symbol, String],
        ?scope: String,
        ?request_options: DockerEngine::request_opts
      ) -> DockerEngine::Models::NetworkCreateResponse

      def list: (
        ?filters: String,
        ?request_options: DockerEngine::request_opts
      ) -> DockerEngine::Models::network_list_response

      def delete: (
        String id,
        ?request_options: DockerEngine::request_opts
      ) -> nil

      def inspect_: (
        String id,
        ?scope: String,
        ?verbose: bool,
        ?request_options: DockerEngine::request_opts
      ) -> DockerEngine::Models::NetworkInspectResponse

      def initialize: (client: DockerEngine::Client) -> void
    end
  end
end
