module DockerEngine
  module Resources
    class Nodes
      def update: (
        String id,
        version: Integer,
        ?spec: DockerEngine::Spec,
        ?request_options: DockerEngine::request_opts
      ) -> nil

      def list: (
        ?filters: String,
        ?request_options: DockerEngine::request_opts
      ) -> DockerEngine::Models::node_list_response

      def delete: (
        String id,
        ?force: bool,
        ?request_options: DockerEngine::request_opts
      ) -> nil

      def inspect_: (
        String id,
        ?request_options: DockerEngine::request_opts
      ) -> DockerEngine::Node

      def initialize: (client: DockerEngine::Client) -> void
    end
  end
end
