module DockerEngine
  module Resources
    class Secrets
      def create: (
        ?spec: DockerEngine::SecretCreateParams::Spec,
        ?request_options: DockerEngine::request_opts
      ) -> DockerEngine::Models::SecretCreateResponse

      def update: (
        String id,
        version: Integer,
        ?spec: DockerEngine::Spec,
        ?request_options: DockerEngine::request_opts
      ) -> nil

      def list: (
        ?filters: String,
        ?request_options: DockerEngine::request_opts
      ) -> DockerEngine::Models::secret_list_response

      def delete: (
        String id,
        ?request_options: DockerEngine::request_opts
      ) -> nil

      def inspect_: (
        String id,
        ?request_options: DockerEngine::request_opts
      ) -> DockerEngine::Secret

      def initialize: (client: DockerEngine::Client) -> void
    end
  end
end
