module DockerEngine
  module Resources
    class Services
      def create: (
        spec: DockerEngine::ServiceCreateParams::Spec,
        ?x_registry_auth: String,
        ?request_options: DockerEngine::request_opts
      ) -> DockerEngine::Models::ServiceCreateResponse

      def list: (
        ?filters: String,
        ?status: bool,
        ?request_options: DockerEngine::request_opts
      ) -> DockerEngine::Models::service_list_response

      def delete: (
        String id,
        ?request_options: DockerEngine::request_opts
      ) -> nil

      def inspect_: (
        String id,
        ?insert_defaults: bool,
        ?request_options: DockerEngine::request_opts
      ) -> DockerEngine::Service

      def initialize: (client: DockerEngine::Client) -> void
    end
  end
end
