module DockerEngine
  module Resources
    class Tasks
      def list: (
        ?filters: String,
        ?request_options: DockerEngine::request_opts
      ) -> DockerEngine::Models::task_list_response

      def inspect_: (
        String id,
        ?request_options: DockerEngine::request_opts
      ) -> DockerEngine::Task

      def logs: (
        String id,
        ?details: bool,
        ?follow: bool,
        ?since: Integer,
        ?stderr: bool,
        ?stdout: bool,
        ?tail: String,
        ?timestamps: bool,
        ?request_options: DockerEngine::request_opts
      ) -> StringIO

      def initialize: (client: DockerEngine::Client) -> void
    end
  end
end
