module Docker
  class Client < Docker::Internal::Transport::BaseClient
    DEFAULT_MAX_RETRIES: 2

    DEFAULT_TIMEOUT_IN_SECONDS: Float

    DEFAULT_INITIAL_RETRY_DELAY: Float

    DEFAULT_MAX_RETRY_DELAY: Float

    attr_reader auth: Docker::Resources::Auth

    attr_reader system_: Docker::Resources::System

    attr_reader containers: Docker::Resources::Containers

    attr_reader images: Docker::Resources::Images

    attr_reader networks: Docker::Resources::Networks

    attr_reader volumes: Docker::Resources::Volumes

    attr_reader services: Docker::Resources::Services

    def initialize: (
      ?base_url: String?,
      ?max_retries: Integer,
      ?timeout: Float,
      ?initial_retry_delay: Float,
      ?max_retry_delay: Float
    ) -> void
  end
end
