module Docker
  class AuthLoginParams = Docker::Models::AuthLoginParams

  class AuthResponse = Docker::Models::AuthResponse

  class Config = Docker::Models::Config

  class Container = Docker::Models::Container

  class ContainerCreateParams = Docker::Models::ContainerCreateParams

  class ContainerDeleteParams = Docker::Models::ContainerDeleteParams

  class ContainerInspectParams = Docker::Models::ContainerInspectParams

  class ContainerKillParams = Docker::Models::ContainerKillParams

  class ContainerListParams = Docker::Models::ContainerListParams

  class ContainerLogsParams = Docker::Models::ContainerLogsParams

  class ContainerStartParams = Docker::Models::ContainerStartParams

  class ContainerStopParams = Docker::Models::ContainerStopParams

  class CreateRequest = Docker::Models::CreateRequest

  class CreateResponse = Docker::Models::CreateResponse

  class Error = Docker::Models::Error

  class Image = Docker::Models::Image

  class ImageDeleteParams = Docker::Models::ImageDeleteParams

  class ImageInspectParams = Docker::Models::ImageInspectParams

  class ImageListParams = Docker::Models::ImageListParams

  class ImagePullParams = Docker::Models::ImagePullParams

  class Network = Docker::Models::Network

  class NetworkCreateParams = Docker::Models::NetworkCreateParams

  class NetworkDeleteParams = Docker::Models::NetworkDeleteParams

  class NetworkInspectParams = Docker::Models::NetworkInspectParams

  class NetworkListParams = Docker::Models::NetworkListParams

  class Service = Docker::Models::Service

  class ServiceCreateParams = Docker::Models::ServiceCreateParams

  class ServiceDeleteParams = Docker::Models::ServiceDeleteParams

  class ServiceInspectParams = Docker::Models::ServiceInspectParams

  class ServiceListParams = Docker::Models::ServiceListParams

  class Spec = Docker::Models::Spec

  class Summary = Docker::Models::Summary

  class SystemInfoParams = Docker::Models::SystemInfoParams

  class SystemPingParams = Docker::Models::SystemPingParams

  class SystemVersionParams = Docker::Models::SystemVersionParams

  class Volume = Docker::Models::Volume

  class VolumeCreateParams = Docker::Models::VolumeCreateParams

  class VolumeDeleteParams = Docker::Models::VolumeDeleteParams

  class VolumeInspectParams = Docker::Models::VolumeInspectParams

  class VolumeListParams = Docker::Models::VolumeListParams
end
