module DockerEngineAPI
  module Models
    type container_kill_params =
      { signal: String } & DockerEngineAPI::Internal::Type::request_parameters

    class ContainerKillParams < DockerEngineAPI::Internal::Type::BaseModel
      extend DockerEngineAPI::Internal::Type::RequestParameters::Converter
      include DockerEngineAPI::Internal::Type::RequestParameters

      attr_reader signal: String?

      def signal=: (String) -> String

      def initialize: (
        ?signal: String,
        ?request_options: DockerEngineAPI::request_opts
      ) -> void

      def to_hash: -> {
        signal: String,
        request_options: DockerEngineAPI::RequestOptions
      }
    end
  end
end
