module DockerEngineAPI
  module Models
    type container_exec_params =
      {
        attach_stderr: bool,
        attach_stdin: bool,
        attach_stdout: bool,
        cmd: ::Array[String],
        console_size: ::Array[Integer]?,
        detach_keys: String,
        env: ::Array[String],
        privileged: bool,
        tty: bool,
        user: String,
        working_dir: String
      }
      & DockerEngineAPI::Internal::Type::request_parameters

    class ContainerExecParams < DockerEngineAPI::Internal::Type::BaseModel
      extend DockerEngineAPI::Internal::Type::RequestParameters::Converter
      include DockerEngineAPI::Internal::Type::RequestParameters

      attr_reader attach_stderr: bool?

      def attach_stderr=: (bool) -> bool

      attr_reader attach_stdin: bool?

      def attach_stdin=: (bool) -> bool

      attr_reader attach_stdout: bool?

      def attach_stdout=: (bool) -> bool

      attr_reader cmd: ::Array[String]?

      def cmd=: (::Array[String]) -> ::Array[String]

      attr_accessor console_size: ::Array[Integer]?

      attr_reader detach_keys: String?

      def detach_keys=: (String) -> String

      attr_reader env: ::Array[String]?

      def env=: (::Array[String]) -> ::Array[String]

      attr_reader privileged: bool?

      def privileged=: (bool) -> bool

      attr_reader tty: bool?

      def tty=: (bool) -> bool

      attr_reader user: String?

      def user=: (String) -> String

      attr_reader working_dir: String?

      def working_dir=: (String) -> String

      def initialize: (
        ?attach_stderr: bool,
        ?attach_stdin: bool,
        ?attach_stdout: bool,
        ?cmd: ::Array[String],
        ?console_size: ::Array[Integer]?,
        ?detach_keys: String,
        ?env: ::Array[String],
        ?privileged: bool,
        ?tty: bool,
        ?user: String,
        ?working_dir: String,
        ?request_options: DockerEngineAPI::request_opts
      ) -> void

      def to_hash: -> {
        attach_stderr: bool,
        attach_stdin: bool,
        attach_stdout: bool,
        cmd: ::Array[String],
        console_size: ::Array[Integer]?,
        detach_keys: String,
        env: ::Array[String],
        privileged: bool,
        tty: bool,
        user: String,
        working_dir: String,
        request_options: DockerEngineAPI::RequestOptions
      }
    end
  end
end
