module DockerEngineAPI
  module Models
    type container_start_params =
      { detach_keys: String }
      & DockerEngineAPI::Internal::Type::request_parameters

    class ContainerStartParams < DockerEngineAPI::Internal::Type::BaseModel
      extend DockerEngineAPI::Internal::Type::RequestParameters::Converter
      include DockerEngineAPI::Internal::Type::RequestParameters

      attr_reader detach_keys: String?

      def detach_keys=: (String) -> String

      def initialize: (
        ?detach_keys: String,
        ?request_options: DockerEngineAPI::request_opts
      ) -> void

      def to_hash: -> {
        detach_keys: String,
        request_options: DockerEngineAPI::RequestOptions
      }
    end
  end
end
