module DockerEngineAPI
  module Models
    type container_wait_params =
      { condition: DockerEngineAPI::Models::ContainerWaitParams::condition }
      & DockerEngineAPI::Internal::Type::request_parameters

    class ContainerWaitParams < DockerEngineAPI::Internal::Type::BaseModel
      extend DockerEngineAPI::Internal::Type::RequestParameters::Converter
      include DockerEngineAPI::Internal::Type::RequestParameters

      attr_reader condition: DockerEngineAPI::Models::ContainerWaitParams::condition?

      def condition=: (
        DockerEngineAPI::Models::ContainerWaitParams::condition
      ) -> DockerEngineAPI::Models::ContainerWaitParams::condition

      def initialize: (
        ?condition: DockerEngineAPI::Models::ContainerWaitParams::condition,
        ?request_options: DockerEngineAPI::request_opts
      ) -> void

      def to_hash: -> {
        condition: DockerEngineAPI::Models::ContainerWaitParams::condition,
        request_options: DockerEngineAPI::RequestOptions
      }

      type condition = :"not-running" | :"next-exit" | :removed

      module Condition
        extend DockerEngineAPI::Internal::Type::Enum

        NOT_RUNNING: :"not-running"
        NEXT_EXIT: :"next-exit"
        REMOVED: :removed

        def self?.values: -> ::Array[DockerEngineAPI::Models::ContainerWaitParams::condition]
      end
    end
  end
end
