module DockerEngineAPI
  module Models
    type container_inspect_params =
      { size: bool } & DockerEngineAPI::Internal::Type::request_parameters

    class ContainerInspectParams < DockerEngineAPI::Internal::Type::BaseModel
      extend DockerEngineAPI::Internal::Type::RequestParameters::Converter
      include DockerEngineAPI::Internal::Type::RequestParameters

      attr_reader size: bool?

      def size=: (bool) -> bool

      def initialize: (
        ?size: bool,
        ?request_options: DockerEngineAPI::request_opts
      ) -> void

      def to_hash: -> {
        size: bool,
        request_options: DockerEngineAPI::RequestOptions
      }
    end
  end
end
