module DockerEngineAPI
  module Models
    type container_top_params =
      { ps_args: String } & DockerEngineAPI::Internal::Type::request_parameters

    class ContainerTopParams < DockerEngineAPI::Internal::Type::BaseModel
      extend DockerEngineAPI::Internal::Type::RequestParameters::Converter
      include DockerEngineAPI::Internal::Type::RequestParameters

      attr_reader ps_args: String?

      def ps_args=: (String) -> String

      def initialize: (
        ?ps_args: String,
        ?request_options: DockerEngineAPI::request_opts
      ) -> void

      def to_hash: -> {
        ps_args: String,
        request_options: DockerEngineAPI::RequestOptions
      }
    end
  end
end
