module DockerEngineAPI
  module Models
    type image_commit_params =
      {
        author: String,
        changes: String,
        comment: String,
        container: String,
        pause: bool,
        repo: String,
        tag: String
      }
      & DockerEngineAPI::Internal::Type::request_parameters

    class ImageCommitParams < DockerEngineAPI::Models::Config
      extend DockerEngineAPI::Internal::Type::RequestParameters::Converter
      include DockerEngineAPI::Internal::Type::RequestParameters

      def author: -> String?

      def author=: (String _) -> String

      def changes: -> String?

      def changes=: (String _) -> String

      def comment: -> String?

      def comment=: (String _) -> String

      def container: -> String?

      def container=: (String _) -> String

      def pause: -> bool?

      def pause=: (bool _) -> bool

      def repo: -> String?

      def repo=: (String _) -> String

      def tag: -> String?

      def tag=: (String _) -> String

      def initialize: (
        ?author: String,
        ?changes: String,
        ?comment: String,
        ?container: String,
        ?pause: bool,
        ?repo: String,
        ?tag: String,
        ?request_options: DockerEngineAPI::request_opts
      ) -> void

      def to_hash: -> {
        author: String,
        changes: String,
        comment: String,
        container: String,
        pause: bool,
        repo: String,
        tag: String,
        request_options: DockerEngineAPI::RequestOptions
      }
    end
  end
end
