module DockerEngineAPI
  module Models
    type image_search_params =
      { term: String, filters: String, limit: Integer }
      & DockerEngineAPI::Internal::Type::request_parameters

    class ImageSearchParams < DockerEngineAPI::Internal::Type::BaseModel
      extend DockerEngineAPI::Internal::Type::RequestParameters::Converter
      include DockerEngineAPI::Internal::Type::RequestParameters

      attr_accessor term: String

      attr_reader filters: String?

      def filters=: (String) -> String

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      def initialize: (
        term: String,
        ?filters: String,
        ?limit: Integer,
        ?request_options: DockerEngineAPI::request_opts
      ) -> void

      def to_hash: -> {
        term: String,
        filters: String,
        limit: Integer,
        request_options: DockerEngineAPI::RequestOptions
      }
    end
  end
end
