module DockerEngineAPI
  module Models
    type image_build_prune_response =
      { caches_deleted: ::Array[String], space_reclaimed: Integer }

    class ImageBuildPruneResponse < DockerEngineAPI::Internal::Type::BaseModel
      attr_reader caches_deleted: ::Array[String]?

      def caches_deleted=: (::Array[String]) -> ::Array[String]

      attr_reader space_reclaimed: Integer?

      def space_reclaimed=: (Integer) -> Integer

      def initialize: (
        ?caches_deleted: ::Array[String],
        ?space_reclaimed: Integer
      ) -> void

      def to_hash: -> {
        caches_deleted: ::Array[String],
        space_reclaimed: Integer
      }
    end
  end
end
