module DockerEngineAPI
  module Models
    type image_get_all_params =
      { names: ::Array[String], platform: ::Array[String] }
      & DockerEngineAPI::Internal::Type::request_parameters

    class ImageGetAllParams < DockerEngineAPI::Internal::Type::BaseModel
      extend DockerEngineAPI::Internal::Type::RequestParameters::Converter
      include DockerEngineAPI::Internal::Type::RequestParameters

      attr_reader names: ::Array[String]?

      def names=: (::Array[String]) -> ::Array[String]

      attr_reader platform: ::Array[String]?

      def platform=: (::Array[String]) -> ::Array[String]

      def initialize: (
        ?names: ::Array[String],
        ?platform: ::Array[String],
        ?request_options: DockerEngineAPI::request_opts
      ) -> void

      def to_hash: -> {
        names: ::Array[String],
        platform: ::Array[String],
        request_options: DockerEngineAPI::RequestOptions
      }
    end
  end
end
