module DockerEngineAPI
  module Models
    type image_build_params =
      {
        body: DockerEngineAPI::Internal::file_input,
        buildargs: String,
        cachefrom: String,
        cpuperiod: Integer,
        cpuquota: Integer,
        cpusetcpus: String,
        cpushares: Integer,
        dockerfile: String,
        extrahosts: String,
        forcerm: bool,
        labels: String,
        memory: Integer,
        memswap: Integer,
        networkmode: String,
        nocache: bool,
        outputs: String,
        platform: String,
        pull: String,
        q: bool,
        remote: String,
        rm: bool,
        shmsize: Integer,
        squash: bool,
        t: String,
        target: String,
        version: DockerEngineAPI::Models::ImageBuildParams::version,
        x_registry_config: String
      }
      & DockerEngineAPI::Internal::Type::request_parameters

    class ImageBuildParams < DockerEngineAPI::Internal::Type::BaseModel
      extend DockerEngineAPI::Internal::Type::RequestParameters::Converter
      include DockerEngineAPI::Internal::Type::RequestParameters

      attr_accessor body: DockerEngineAPI::Internal::file_input

      attr_reader buildargs: String?

      def buildargs=: (String) -> String

      attr_reader cachefrom: String?

      def cachefrom=: (String) -> String

      attr_reader cpuperiod: Integer?

      def cpuperiod=: (Integer) -> Integer

      attr_reader cpuquota: Integer?

      def cpuquota=: (Integer) -> Integer

      attr_reader cpusetcpus: String?

      def cpusetcpus=: (String) -> String

      attr_reader cpushares: Integer?

      def cpushares=: (Integer) -> Integer

      attr_reader dockerfile: String?

      def dockerfile=: (String) -> String

      attr_reader extrahosts: String?

      def extrahosts=: (String) -> String

      attr_reader forcerm: bool?

      def forcerm=: (bool) -> bool

      attr_reader labels: String?

      def labels=: (String) -> String

      attr_reader memory: Integer?

      def memory=: (Integer) -> Integer

      attr_reader memswap: Integer?

      def memswap=: (Integer) -> Integer

      attr_reader networkmode: String?

      def networkmode=: (String) -> String

      attr_reader nocache: bool?

      def nocache=: (bool) -> bool

      attr_reader outputs: String?

      def outputs=: (String) -> String

      attr_reader platform: String?

      def platform=: (String) -> String

      attr_reader pull: String?

      def pull=: (String) -> String

      attr_reader q: bool?

      def q=: (bool) -> bool

      attr_reader remote: String?

      def remote=: (String) -> String

      attr_reader rm: bool?

      def rm=: (bool) -> bool

      attr_reader shmsize: Integer?

      def shmsize=: (Integer) -> Integer

      attr_reader squash: bool?

      def squash=: (bool) -> bool

      attr_reader t: String?

      def t=: (String) -> String

      attr_reader target: String?

      def target=: (String) -> String

      attr_reader version: DockerEngineAPI::Models::ImageBuildParams::version?

      def version=: (
        DockerEngineAPI::Models::ImageBuildParams::version
      ) -> DockerEngineAPI::Models::ImageBuildParams::version

      attr_reader x_registry_config: String?

      def x_registry_config=: (String) -> String

      def initialize: (
        body: DockerEngineAPI::Internal::file_input,
        ?buildargs: String,
        ?cachefrom: String,
        ?cpuperiod: Integer,
        ?cpuquota: Integer,
        ?cpusetcpus: String,
        ?cpushares: Integer,
        ?dockerfile: String,
        ?extrahosts: String,
        ?forcerm: bool,
        ?labels: String,
        ?memory: Integer,
        ?memswap: Integer,
        ?networkmode: String,
        ?nocache: bool,
        ?outputs: String,
        ?platform: String,
        ?pull: String,
        ?q: bool,
        ?remote: String,
        ?rm: bool,
        ?shmsize: Integer,
        ?squash: bool,
        ?t: String,
        ?target: String,
        ?version: DockerEngineAPI::Models::ImageBuildParams::version,
        ?x_registry_config: String,
        ?request_options: DockerEngineAPI::request_opts
      ) -> void

      def to_hash: -> {
        body: DockerEngineAPI::Internal::file_input,
        buildargs: String,
        cachefrom: String,
        cpuperiod: Integer,
        cpuquota: Integer,
        cpusetcpus: String,
        cpushares: Integer,
        dockerfile: String,
        extrahosts: String,
        forcerm: bool,
        labels: String,
        memory: Integer,
        memswap: Integer,
        networkmode: String,
        nocache: bool,
        outputs: String,
        platform: String,
        pull: String,
        q: bool,
        remote: String,
        rm: bool,
        shmsize: Integer,
        squash: bool,
        t: String,
        target: String,
        version: DockerEngineAPI::Models::ImageBuildParams::version,
        x_registry_config: String,
        request_options: DockerEngineAPI::RequestOptions
      }

      type version = :"1" | :"2"

      module Version
        extend DockerEngineAPI::Internal::Type::Enum

        VERSION_1: :"1"
        VERSION_2: :"2"

        def self?.values: -> ::Array[DockerEngineAPI::Models::ImageBuildParams::version]
      end
    end
  end
end
