module DockerEngineAPI
  module Models
    type image_history_params =
      { platform: String } & DockerEngineAPI::Internal::Type::request_parameters

    class ImageHistoryParams < DockerEngineAPI::Internal::Type::BaseModel
      extend DockerEngineAPI::Internal::Type::RequestParameters::Converter
      include DockerEngineAPI::Internal::Type::RequestParameters

      attr_reader platform: String?

      def platform=: (String) -> String

      def initialize: (
        ?platform: String,
        ?request_options: DockerEngineAPI::request_opts
      ) -> void

      def to_hash: -> {
        platform: String,
        request_options: DockerEngineAPI::RequestOptions
      }
    end
  end
end
