module DockerEngineAPI
  module Models
    type image_load_params =
      {
        body: DockerEngineAPI::Internal::file_input,
        platform: ::Array[String],
        quiet: bool
      }
      & DockerEngineAPI::Internal::Type::request_parameters

    class ImageLoadParams < DockerEngineAPI::Internal::Type::BaseModel
      extend DockerEngineAPI::Internal::Type::RequestParameters::Converter
      include DockerEngineAPI::Internal::Type::RequestParameters

      attr_accessor body: DockerEngineAPI::Internal::file_input

      attr_reader platform: ::Array[String]?

      def platform=: (::Array[String]) -> ::Array[String]

      attr_reader quiet: bool?

      def quiet=: (bool) -> bool

      def initialize: (
        body: DockerEngineAPI::Internal::file_input,
        ?platform: ::Array[String],
        ?quiet: bool,
        ?request_options: DockerEngineAPI::request_opts
      ) -> void

      def to_hash: -> {
        body: DockerEngineAPI::Internal::file_input,
        platform: ::Array[String],
        quiet: bool,
        request_options: DockerEngineAPI::RequestOptions
      }
    end
  end
end
