module DockerEngineAPI
  module Models
    type list_response =
      { volumes: ::Array[DockerEngineAPI::Volume], warnings: ::Array[String] }

    class ListResponse < DockerEngineAPI::Internal::Type::BaseModel
      attr_reader volumes: ::Array[DockerEngineAPI::Volume]?

      def volumes=: (
        ::Array[DockerEngineAPI::Volume]
      ) -> ::Array[DockerEngineAPI::Volume]

      attr_reader warnings: ::Array[String]?

      def warnings=: (::Array[String]) -> ::Array[String]

      def initialize: (
        ?volumes: ::Array[DockerEngineAPI::Volume],
        ?warnings: ::Array[String]
      ) -> void

      def to_hash: -> {
        volumes: ::Array[DockerEngineAPI::Volume],
        warnings: ::Array[String]
      }
    end
  end
end
