module DockerEngineAPI
  module Models
    type network_inspect_params =
      { scope: String, verbose: bool }
      & DockerEngineAPI::Internal::Type::request_parameters

    class NetworkInspectParams < DockerEngineAPI::Internal::Type::BaseModel
      extend DockerEngineAPI::Internal::Type::RequestParameters::Converter
      include DockerEngineAPI::Internal::Type::RequestParameters

      attr_reader scope: String?

      def scope=: (String) -> String

      attr_reader verbose: bool?

      def verbose=: (bool) -> bool

      def initialize: (
        ?scope: String,
        ?verbose: bool,
        ?request_options: DockerEngineAPI::request_opts
      ) -> void

      def to_hash: -> {
        scope: String,
        verbose: bool,
        request_options: DockerEngineAPI::RequestOptions
      }
    end
  end
end
