module DockerEngineAPI
  module Models
    type plugin_set_params =
      { body: ::Array[String] }
      & DockerEngineAPI::Internal::Type::request_parameters

    class PluginSetParams < DockerEngineAPI::Internal::Type::BaseModel
      extend DockerEngineAPI::Internal::Type::RequestParameters::Converter
      include DockerEngineAPI::Internal::Type::RequestParameters

      attr_reader body: ::Array[String]?

      def body=: (::Array[String]) -> ::Array[String]

      def initialize: (
        ?body: ::Array[String],
        ?request_options: DockerEngineAPI::request_opts
      ) -> void

      def to_hash: -> {
        body: ::Array[String],
        request_options: DockerEngineAPI::RequestOptions
      }
    end
  end
end
