module DockerEngineAPI
  module Models
    type plugin_privileges_params =
      { remote: String } & DockerEngineAPI::Internal::Type::request_parameters

    class PluginPrivilegesParams < DockerEngineAPI::Internal::Type::BaseModel
      extend DockerEngineAPI::Internal::Type::RequestParameters::Converter
      include DockerEngineAPI::Internal::Type::RequestParameters

      attr_accessor remote: String

      def initialize: (
        remote: String,
        ?request_options: DockerEngineAPI::request_opts
      ) -> void

      def to_hash: -> {
        remote: String,
        request_options: DockerEngineAPI::RequestOptions
      }
    end
  end
end
