module DockerEngineAPI
  module Models
    type secret =
      {
        created_at: String,
        id: String,
        spec: DockerEngineAPI::Spec,
        updated_at: String,
        version: DockerEngineAPI::Secret::Version
      }

    class Secret < DockerEngineAPI::Internal::Type::BaseModel
      attr_reader created_at: String?

      def created_at=: (String) -> String

      attr_reader id: String?

      def id=: (String) -> String

      attr_reader spec: DockerEngineAPI::Spec?

      def spec=: (DockerEngineAPI::Spec) -> DockerEngineAPI::Spec

      attr_reader updated_at: String?

      def updated_at=: (String) -> String

      attr_reader version: DockerEngineAPI::Secret::Version?

      def version=: (
        DockerEngineAPI::Secret::Version
      ) -> DockerEngineAPI::Secret::Version

      def initialize: (
        ?created_at: String,
        ?id: String,
        ?spec: DockerEngineAPI::Spec,
        ?updated_at: String,
        ?version: DockerEngineAPI::Secret::Version
      ) -> void

      def to_hash: -> {
        created_at: String,
        id: String,
        spec: DockerEngineAPI::Spec,
        updated_at: String,
        version: DockerEngineAPI::Secret::Version
      }

      type version = { index: Integer }

      class Version < DockerEngineAPI::Internal::Type::BaseModel
        attr_reader index: Integer?

        def index=: (Integer) -> Integer

        def initialize: (?index: Integer) -> void

        def to_hash: -> { index: Integer }
      end
    end
  end
end
