module DockerEngineAPI
  module Models
    type service_update_params =
      {
        version: Integer,
        spec: DockerEngineAPI::ServiceUpdateParams::Spec,
        registry_auth_from: DockerEngineAPI::Models::ServiceUpdateParams::registry_auth_from,
        rollback: String,
        x_registry_auth: String
      }
      & DockerEngineAPI::Internal::Type::request_parameters

    class ServiceUpdateParams < DockerEngineAPI::Internal::Type::BaseModel
      extend DockerEngineAPI::Internal::Type::RequestParameters::Converter
      include DockerEngineAPI::Internal::Type::RequestParameters

      attr_accessor version: Integer

      attr_accessor spec: DockerEngineAPI::ServiceUpdateParams::Spec

      attr_reader registry_auth_from: DockerEngineAPI::Models::ServiceUpdateParams::registry_auth_from?

      def registry_auth_from=: (
        DockerEngineAPI::Models::ServiceUpdateParams::registry_auth_from
      ) -> DockerEngineAPI::Models::ServiceUpdateParams::registry_auth_from

      attr_reader rollback: String?

      def rollback=: (String) -> String

      attr_reader x_registry_auth: String?

      def x_registry_auth=: (String) -> String

      def initialize: (
        version: Integer,
        spec: DockerEngineAPI::ServiceUpdateParams::Spec,
        ?registry_auth_from: DockerEngineAPI::Models::ServiceUpdateParams::registry_auth_from,
        ?rollback: String,
        ?x_registry_auth: String,
        ?request_options: DockerEngineAPI::request_opts
      ) -> void

      def to_hash: -> {
        version: Integer,
        spec: DockerEngineAPI::ServiceUpdateParams::Spec,
        registry_auth_from: DockerEngineAPI::Models::ServiceUpdateParams::registry_auth_from,
        rollback: String,
        x_registry_auth: String,
        request_options: DockerEngineAPI::RequestOptions
      }

      type spec = {  }

      class Spec < DockerEngineAPI::Models::Spec
        def initialize: -> void

        def to_hash: -> {  }
      end

      type registry_auth_from = :spec | :"previous-spec"

      module RegistryAuthFrom
        extend DockerEngineAPI::Internal::Type::Enum

        SPEC: :spec
        PREVIOUS_SPEC: :"previous-spec"

        def self?.values: -> ::Array[DockerEngineAPI::Models::ServiceUpdateParams::registry_auth_from]
      end
    end
  end
end
