module DockerEngineAPI
  module Models
    type swarm_unlock_params =
      { unlock_key: String }
      & DockerEngineAPI::Internal::Type::request_parameters

    class SwarmUnlockParams < DockerEngineAPI::Internal::Type::BaseModel
      extend DockerEngineAPI::Internal::Type::RequestParameters::Converter
      include DockerEngineAPI::Internal::Type::RequestParameters

      attr_reader unlock_key: String?

      def unlock_key=: (String) -> String

      def initialize: (
        ?unlock_key: String,
        ?request_options: DockerEngineAPI::request_opts
      ) -> void

      def to_hash: -> {
        unlock_key: String,
        request_options: DockerEngineAPI::RequestOptions
      }
    end
  end
end
