module DockerEngineAPI
  module Models
    type swarm_leave_params =
      { force: bool } & DockerEngineAPI::Internal::Type::request_parameters

    class SwarmLeaveParams < DockerEngineAPI::Internal::Type::BaseModel
      extend DockerEngineAPI::Internal::Type::RequestParameters::Converter
      include DockerEngineAPI::Internal::Type::RequestParameters

      attr_reader force: bool?

      def force=: (bool) -> bool

      def initialize: (
        ?force: bool,
        ?request_options: DockerEngineAPI::request_opts
      ) -> void

      def to_hash: -> {
        force: bool,
        request_options: DockerEngineAPI::RequestOptions
      }
    end
  end
end
