module DockerEngineAPI
  module Models
    type system_data_usage_params =
      {
        type: ::Array[DockerEngineAPI::Models::SystemDataUsageParams::type_],
        verbose: bool
      }
      & DockerEngineAPI::Internal::Type::request_parameters

    class SystemDataUsageParams < DockerEngineAPI::Internal::Type::BaseModel
      extend DockerEngineAPI::Internal::Type::RequestParameters::Converter
      include DockerEngineAPI::Internal::Type::RequestParameters

      attr_reader type: ::Array[DockerEngineAPI::Models::SystemDataUsageParams::type_]?

      def type=: (
        ::Array[DockerEngineAPI::Models::SystemDataUsageParams::type_]
      ) -> ::Array[DockerEngineAPI::Models::SystemDataUsageParams::type_]

      attr_reader verbose: bool?

      def verbose=: (bool) -> bool

      def initialize: (
        ?type: ::Array[DockerEngineAPI::Models::SystemDataUsageParams::type_],
        ?verbose: bool,
        ?request_options: DockerEngineAPI::request_opts
      ) -> void

      def to_hash: -> {
        type: ::Array[DockerEngineAPI::Models::SystemDataUsageParams::type_],
        verbose: bool,
        request_options: DockerEngineAPI::RequestOptions
      }

      type type_ = :container | :image | :volume | :"build-cache"

      module Type
        extend DockerEngineAPI::Internal::Type::Enum

        CONTAINER: :container
        IMAGE: :image
        VOLUME: :volume
        BUILD_CACHE: :"build-cache"

        def self?.values: -> ::Array[DockerEngineAPI::Models::SystemDataUsageParams::type_]
      end
    end
  end
end
