module DockerEngineAPI
  module Models
    type system_events_response =
      {
        action: String,
        actor: DockerEngineAPI::Models::SystemEventsResponse::Actor,
        scope: DockerEngineAPI::Models::SystemEventsResponse::scope,
        time: Integer,
        time_nano: Integer,
        type: DockerEngineAPI::Models::SystemEventsResponse::type_
      }

    class SystemEventsResponse < DockerEngineAPI::Internal::Type::BaseModel
      attr_reader action: String?

      def action=: (String) -> String

      attr_reader actor: DockerEngineAPI::Models::SystemEventsResponse::Actor?

      def actor=: (
        DockerEngineAPI::Models::SystemEventsResponse::Actor
      ) -> DockerEngineAPI::Models::SystemEventsResponse::Actor

      attr_reader scope: DockerEngineAPI::Models::SystemEventsResponse::scope?

      def scope=: (
        DockerEngineAPI::Models::SystemEventsResponse::scope
      ) -> DockerEngineAPI::Models::SystemEventsResponse::scope

      attr_reader time: Integer?

      def time=: (Integer) -> Integer

      attr_reader time_nano: Integer?

      def time_nano=: (Integer) -> Integer

      attr_reader type: DockerEngineAPI::Models::SystemEventsResponse::type_?

      def type=: (
        DockerEngineAPI::Models::SystemEventsResponse::type_
      ) -> DockerEngineAPI::Models::SystemEventsResponse::type_

      def initialize: (
        ?action: String,
        ?actor: DockerEngineAPI::Models::SystemEventsResponse::Actor,
        ?scope: DockerEngineAPI::Models::SystemEventsResponse::scope,
        ?time: Integer,
        ?time_nano: Integer,
        ?type: DockerEngineAPI::Models::SystemEventsResponse::type_
      ) -> void

      def to_hash: -> {
        action: String,
        actor: DockerEngineAPI::Models::SystemEventsResponse::Actor,
        scope: DockerEngineAPI::Models::SystemEventsResponse::scope,
        time: Integer,
        time_nano: Integer,
        type: DockerEngineAPI::Models::SystemEventsResponse::type_
      }

      type actor = { attributes: ::Hash[Symbol, String], id: String }

      class Actor < DockerEngineAPI::Internal::Type::BaseModel
        attr_reader attributes: ::Hash[Symbol, String]?

        def attributes=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        attr_reader id: String?

        def id=: (String) -> String

        def initialize: (
          ?attributes: ::Hash[Symbol, String],
          ?id: String
        ) -> void

        def to_hash: -> { attributes: ::Hash[Symbol, String], id: String }
      end

      type scope = :local | :swarm

      module Scope
        extend DockerEngineAPI::Internal::Type::Enum

        LOCAL: :local
        SWARM: :swarm

        def self?.values: -> ::Array[DockerEngineAPI::Models::SystemEventsResponse::scope]
      end

      type type_ =
        :builder
        | :config
        | :container
        | :daemon
        | :image
        | :network
        | :node
        | :plugin
        | :secret
        | :service
        | :volume

      module Type
        extend DockerEngineAPI::Internal::Type::Enum

        BUILDER: :builder
        CONFIG: :config
        CONTAINER: :container
        DAEMON: :daemon
        IMAGE: :image
        NETWORK: :network
        NODE: :node
        PLUGIN: :plugin
        SECRET: :secret
        SERVICE: :service
        VOLUME: :volume

        def self?.values: -> ::Array[DockerEngineAPI::Models::SystemEventsResponse::type_]
      end
    end
  end
end
