module DockerEngineAPI
  module Models
    type system_info_params =
      {  } & DockerEngineAPI::Internal::Type::request_parameters

    class SystemInfoParams < DockerEngineAPI::Internal::Type::BaseModel
      extend DockerEngineAPI::Internal::Type::RequestParameters::Converter
      include DockerEngineAPI::Internal::Type::RequestParameters

      def initialize: (?request_options: DockerEngineAPI::request_opts) -> void

      def to_hash: -> { request_options: DockerEngineAPI::RequestOptions }
    end
  end
end
