module DockerEngineAPI
  module Models
    type top_response =
      { processes: ::Array[::Array[String]], titles: ::Array[String] }

    class TopResponse < DockerEngineAPI::Internal::Type::BaseModel
      attr_reader processes: ::Array[::Array[String]]?

      def processes=: (::Array[::Array[String]]) -> ::Array[::Array[String]]

      attr_reader titles: ::Array[String]?

      def titles=: (::Array[String]) -> ::Array[String]

      def initialize: (
        ?processes: ::Array[::Array[String]],
        ?titles: ::Array[String]
      ) -> void

      def to_hash: -> {
        processes: ::Array[::Array[String]],
        titles: ::Array[String]
      }
    end
  end
end
